### ISSUE TITLE
103.31.236.0解析不准，但IP138是准的

### ISSUE THREAD

**Issue by yuanhaoliang** [lionsoul2014/ip2region#10]
从这个IP库里查到的信息是：
19|孟加拉国|0|0|0|0

从ip138得到的是：
http://www.ip138.com/ips138.asp?ip=103.31.236.0&action=2
黑龙江省哈尔滨市 联通

请问能否合并一下ip138的IP库呢？

**Comment by lionsoul2014** [comment]
这个数据源的数据可以参考！
你这边可以确保103.31.236.0这个地址是黑龙江的吗？
