### ISSUE TITLE
自己生成的ip.merge.txt创建的ip2region.db，查找数据提示[Error]: Data pointer not found，请问ip.merge.txt文件的写入有什么编码要求吗？

### ISSUE THREAD

**Issue by ymb1991** [lionsoul2014/ip2region#101]
生成的ip.merge.txt中的内容格式为：064.059.179.022|064.059.179.022|加拿大|0|萨斯喀彻温省|穆斯乔|其他

**Comment by ymb1991** [comment]
生成的ip.merge.txt中的内容格式为：064.059.179.022|064.059.179.022|加拿大|0|萨斯喀彻温省|穆斯乔|其他

**Comment by lionsoul2014** [comment]
ip.merge.txt格式要求如下：

1、一定要是UTF-8编码的。
2、一个ip范围一样。
3、ip地址的每个byte要求使用十进制，例如上面的064.059.179.022，前面的0就不行。
