### ISSUE TITLE
too many open files问题

### ISSUE THREAD

**Issue by zx8329200** [lionsoul2014/ip2region#103]
一开始运行是没问题的，大概过10几个小时之后疯狂报too many open files错误。可以知道原因吗？？

**Comment by lionsoul2014** [comment]
这个很大程度上和ip2region没有关系。

如果是Java，并发可以如下解决：
1、使用memory算法，启动程序的时候初始化，然后searcher对象可以并发调用。
2、其他算法每个线程一个searcher对象，使用完后记得close掉，不然就会报上面的错误。

其他语言一样，记得创建的searcher对象，使用完后记得close掉。

**Comment by or1annai** [comment]
在flink中调用时出现了too many open files的问题，在流处理中会多次新建Dbsearcher对象，但是每次都会close掉，用的是MEMORY_ALGORITYM算法，是不是不能多次新建Dbsearcher对象

**Comment by lionsoul2014** [comment]
用新版本的 xdb，Memory模式创建全局模式，一个实例即可。
