### ISSUE TITLE
怎么做到程序自动更新数据库

### ISSUE THREAD

**Issue by 459217974** [lionsoul2014/ip2region#107]
我可以定时从 github 拉取你的DB文件更新 IP 库嘛，这样做的问题是，你的数据库格式会不会变导致新的数据库老的代码不能使用。
还有一个问题是，这个 merge.txt 跟 db 是什么关系，merge.txt 里就包含了 db 里所有的数据嘛，还是说这个是增量更新的文件，生成的时候会把 merge.txt 里的合并到已有数据库。

**Comment by lionsoul2014** [comment]
1, ip2region.db文件是向前兼容的。
2, merge.txt的生成是覆盖式的，merge.txt就是全部的数据，生成的ip2region.db是便于查询，每次都是重新生成！
