### ISSUE TITLE
数据问题

### ISSUE THREAD

**Issue by km3945** [lionsoul2014/ip2region#109]
1.下载的最新版本,/data/ip2region.db 这文件是不是已经用最新数据编译好的.还是要自己在编译一次获得?
2. ip: 154.209.1.161 用百度查是香港地区,用你的查是美国
3. 我编译的PHP7扩展,怎么没有memorySearch方法?

**Comment by lionsoul2014** [comment]
1、下载db文件默认就是最新的数据。
2、这个应该是香港的，错误无法避免。
3、PHP扩展每次都会加载db文件的，不适合使用memory方法！
