### ISSUE TITLE
我写了个可以自动更新数据库的Python的例子，然后优化了Python版本的性能

### ISSUE THREAD

**Issue by 459217974** [lionsoul2014/ip2region#110]
我把项目上传到github了 https://github.com/459217974/ip2region
readme感谢了本项目，不知道您是否同意我发布，要是有问题的话我就把我的删了。谢谢！

**Comment by lionsoul2014** [comment]
没问题，欢迎加入开源的世界，感谢你的贡献，你也可以尝试整理一下合并到这里！
