### ISSUE TITLE
npm 安装失败

### ISSUE THREAD

**Issue by mouse123** [lionsoul2014/ip2region#113]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\RJ-CS\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'lionsoul-ip2region' ]
2 info using npm@6.9.0
3 info using node@v8.11.2
4 verbose npm-session e938b4d80024a538
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://registry.npmjs.org/lionsoul-ip2region 1285ms
8 silly fetchPackageMetaData error for lionsoul-ip2region@latest No valid versions available for lionsoul-ip2region
9 timing stage:rollbackFailedOptional Completed in 0ms
10 timing stage:runTopLevelLifecycles Completed in 14088ms
11 verbose type tag
12 verbose stack lionsoul-ip2region: No valid versions available for lionsoul-ip2region
12 verbose stack     at pickManifest (C:\Users\RJ-CS\AppData\Roaming\npm\node_modules\npm\node_modules\npm-pick-manifest\index.js:36:11)
12 verbose stack     at fetchPackument.then.packument (C:\Users\RJ-CS\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\lib\fetchers\registry\manifest.js:24:14)
12 verbose stack     at tryCatcher (C:\Users\RJ-CS\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
12 verbose stack     at Promise._settlePromiseFromHandler (C:\Users\RJ-CS\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
12 verbose stack     at Promise._settlePromise (C:\Users\RJ-CS\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
12 verbose stack     at Promise._settlePromise0 (C:\Users\RJ-CS\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
12 verbose stack     at Promise._settlePromises (C:\Users\RJ-CS\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:694:18)
12 verbose stack     at _drainQueueStep (C:\Users\RJ-CS\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:138:12)
12 verbose stack     at _drainQueue (C:\Users\RJ-CS\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:131:9)
12 verbose stack     at Async._drainQueues (C:\Users\RJ-CS\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:147:5)
12 verbose stack     at Immediate.Async.drainQueues (C:\Users\RJ-CS\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
12 verbose stack     at runCallback (timers.js:810:20)
12 verbose stack     at tryOnImmediate (timers.js:768:5)
12 verbose stack     at processImmediate [as _immediateCallback] (timers.js:745:5)
13 verbose cwd C:\Users\RJ-CS\Desktop\newWebserver
14 verbose Windows_NT 10.0.16299
15 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\RJ-CS\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "lionsoul-ip2region"
16 verbose node v8.11.2
17 verbose npm  v6.9.0
18 error code ENOVERSIONS
19 error No valid versions available for lionsoul-ip2region
20 verbose exit [ 1, true ]

**Comment by lionsoul2014** [comment]
@dongyado @Maledong @Chunlin-Li 哪位有空看下什么问题。

**Comment by leo3349** [comment]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   'lionsoul-ip2region',
1 verbose cli   '--save' ]
2 info using npm@6.9.0
3 info using node@v10.16.0
4 verbose npm-session d0f044b599234750
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/lionsoul-ip2region 1662ms (from cache)
8 silly fetchPackageMetaData error for lionsoul-ip2region@latest No valid versions available for lionsoul-ip2region
9 timing stage:rollbackFailedOptional Completed in 0ms
10 timing stage:runTopLevelLifecycles Completed in 2025ms
11 verbose type tag
12 verbose stack lionsoul-ip2region: No valid versions available for lionsoul-ip2region
12 verbose stack     at pickManifest (/usr/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:36:11)
12 verbose stack     at fetchPackument.then.packument (/usr/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/manifest.js:24:14)
12 verbose stack     at tryCatcher (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
12 verbose stack     at Promise._settlePromiseFromHandler (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
12 verbose stack     at Promise._settlePromise (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
12 verbose stack     at Promise._settlePromise0 (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
12 verbose stack     at Promise._settlePromises (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:694:18)
12 verbose stack     at _drainQueueStep (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:138:12)
12 verbose stack     at _drainQueue (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:131:9)
12 verbose stack     at Async._drainQueues (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:147:5)
12 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
12 verbose stack     at runCallback (timers.js:705:18)
12 verbose stack     at tryOnImmediate (timers.js:676:5)
12 verbose stack     at processImmediate (timers.js:658:5)
13 verbose cwd /home/a/project/node/inboundMS
14 verbose Linux 4.15.0-20-generic
15 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "lionsoul-ip2region" "--save"
16 verbose node v10.16.0
17 verbose npm  v6.9.0
18 error code ENOVERSIONS
19 error No valid versions available for lionsoul-ip2region
20 verbose exit [ 1, true ]

**Comment by mouse123** [comment]
目前解决方法是到仓库npm安装
![image](https://user-images.githubusercontent.com/21336685/59009015-ac44bc80-885e-11e9-9c08-e7c81f718d3c.png)

**Comment by mouse123** [comment]
但是这个版本好像没带db文件需要自己拷贝一份

**Comment by liudonghua123** [comment]
已经三年没更新了，里面数据文件的路劲都变了
希望可以同步更新一下 npm、pypi、crates 等
