### ISSUE TITLE
DbSearcher构造函数问题

### ISSUE THREAD

**Issue by Echo-ng** [lionsoul2014/ip2region#115]
public DbSearcher(DbConfig dbConfig, byte[] dbBinStr) {
        this.dbConfig = dbConfig;
        this.dbBinStr = dbBinStr;
        this.firstIndexPtr = Util.getIntLong(dbBinStr, 0);
        this.lastIndexPtr = Util.getIntLong(dbBinStr, 4);
        this.totalIndexBlocks = (int)((this.lastIndexPtr - this.firstIndexPtr) / (long)IndexBlock.getIndexBlockLength()) + 1;
    }

这个构造函数没有初始化raf成员，导致在btreeSearch查询的时候出现空指针异常

**Comment by lionsoul2014** [comment]
文档没有写清楚，如果是通过这种方式构造DbSearcher对象，就没必要使用Btree或者Binary算法了，直接使用Memory了，这个构造方法是为Memory算法提供的。

**Comment by Echo-ng** [comment]
好的，谢谢
