### ISSUE TITLE
关于Java使用时的线程安全问题

### ISSUE THREAD

**Issue by fly-china** [lionsoul2014/ip2region#118]
> 全部binding的各个search接口都不是线程安全的实现，不同线程可以通过创建不同的查询对象来使用。

文中所说的线程不安全，是指构建出来的DbSearcher对象就是不安全的，不能使用全局DbSearcher对象，每个线程都需要构建DbSearcher对象吗？我看DbSearcher对象的构造，需要加载6M多的db文件，那岂不是效率很慢。
想请问下，如何构造线程安全的用法？

**Comment by zhongyueming1121** [comment]
就拿memorySearch这个方法来说吧，
```
dbBinStr = new byte[(int) raf.length()]; 
            raf.seek(0L);
            raf.readFully(dbBinStr, 0, dbBinStr.length);
```
这个文件指针偏移，多线程会影响文件读取，可以改成这样：
```
if (dbBinStr == null) {
                synchronized (this) {
                    if (dbBinStr == null) {
                        dbBinStr = new byte[(int) raf.length()];
                        raf.seek(0L);
                        raf.readFully(dbBinStr, 0, dbBinStr.length);
                        //initialize the global vars
                        firstIndexPtr = Util.getIntLong(dbBinStr, 0);
                        long lastIndexPtr = Util.getIntLong(dbBinStr, 4);
                        totalIndexBlocks = (int) ((lastIndexPtr - firstIndexPtr) / blen) + 1;
                    }
}
```

**Comment by lionsoul2014** [comment]
> > 全部binding的各个search接口都不是线程安全的实现，不同线程可以通过创建不同的查询对象来使用。
> 
> 文中所说的线程不安全，是指构建出来的DbSearcher对象就是不安全的，不能使用全局DbSearcher对象，每个线程都需要构建DbSearcher对象吗？我看DbSearcher对象的构造，需要加载6M多的db文件，那岂不是效率很慢。
> 想请问下，如何构造线程安全的用法？

信息有误，每次构造DbSearcher对象，不需要加载6M的文件的，只需要加载一点点。

**Comment by lionsoul2014** [comment]
@fly-china @zhongyueming1121 建议按照现在的方式去用，每个线程构造一个DbSearcher查询对象。如果想要预先加载资源，然后全局使用，建议使用DbSearcher的传入byte[]的构造方法，预先查询一次，就可以安全的用于并发，而且性能也非常高，缺点就是db文件更新了，服务的重启或者需要主动的更新byte[]数据。

**Comment by lionsoul2014** [comment]
> 就拿memorySearch这个方法来说吧，
> 
> ```
> dbBinStr = new byte[(int) raf.length()]; 
>             raf.seek(0L);
>             raf.readFully(dbBinStr, 0, dbBinStr.length);
> ```
> 
> 这个文件指针偏移，多线程会影响文件读取，可以改成这样：
> 
> ```
> if (dbBinStr == null) {
>                 synchronized (this) {
>                     if (dbBinStr == null) {
>                         dbBinStr = new byte[(int) raf.length()];
>                         raf.seek(0L);
>                         raf.readFully(dbBinStr, 0, dbBinStr.length);
>                         //initialize the global vars
>                         firstIndexPtr = Util.getIntLong(dbBinStr, 0);
>                         long lastIndexPtr = Util.getIntLong(dbBinStr, 4);
>                         totalIndexBlocks = (int) ((lastIndexPtr - firstIndexPtr) / blen) + 1;
>                     }
> }
> ```

memorySearch在发布DbSearcher对象前，进行一次预查询，可以安全的用于并发，文档有提到。
