### ISSUE TITLE
php 扩展问题

### ISSUE THREAD

**Issue by km3945** [lionsoul2014/ip2region#12]
想请教下php 扩展,
扩展在加载数据文件时,
是一次加载后长驻?
还是每次调用都读一次?
1.如果是每次都读数据文件,那是否可以通过设置搞成长驻的.

因为我部份脚本应用时,需要长驻.也就是你的mem方式

**Comment by lionsoul2014** [comment]
memory模式是一种新的模式，貌似扩展还没有提供该接口。
`
/* {{{ ip2region_class_functions[]
 *
 * Every user visible function must have an entry in ip2region_functions[].
 */
const zend_function_entry ip2region_class_functions[] = {
	PHP_ME( ip2region_class_entry_ptr,  btreeSearchString,  NULL, ZEND_ACC_PUBLIC | ZEND_ACC_STATIC)
	PHP_ME( ip2region_class_entry_ptr,  binarySearchString, NULL, ZEND_ACC_PUBLIC | ZEND_ACC_STATIC )
	PHP_ME( ip2region_class_entry_ptr,  btreeSearch,  NULL, ZEND_ACC_PUBLIC | ZEND_ACC_STATIC)
	PHP_ME( ip2region_class_entry_ptr,  binarySearch, NULL, ZEND_ACC_PUBLIC | ZEND_ACC_STATIC )
	PHP_FE_END	/* Must be the last line in ip2region_functions[] */
};
/* }}} */
`
如果增加该接口肯定是在模块启动的时候加载常驻内存的！
php版本如果不是在cli模式或者类似的模式，内存模式意义不大。

**Comment by lionsoul2014** [comment]
不是并发特别大的情况下，php版本的btree模式完全可以满足要求！
正式因为扩展模式需要在模块启动函数中加载ip2region.db文件，所以一直没有增加该模式，因为对于不需要使用memory模式的用户，这个会浪费内存，并发情况下的fpm大规模的kill和重启会影响性能。

如果你的项目需要，在ip2region.c里面注册该函数，然后顺便调用一次memorySearch即可加载ip2region.db文件到内存中。

**Comment by jasonhe88** [comment]
因为现在PHP有一个swoole扩展用来常驻内存服务，所以memory search还是很有用的，希望能够加进去

**Comment by lionsoul2014** [comment]
> 因为现在PHP有一个swoole扩展用来常驻内存服务，所以memory search还是很有用的，希望能够加进去

swoole的场景使用纯php写的客户端也是可以的

**Comment by jasonhe88** [comment]
比较了一下纯PHP客户端和扩展的的性能，还是差蛮远的。不过自己把memory search加到扩展里了，很容易。谢谢搞出这么好用的东东!
