### ISSUE TITLE
IP库整合规则

### ISSUE THREAD

**Issue by timegoby** [lionsoul2014/ip2region#126]
请问下这个项目IP库的整合规则大概是怎样的？

**Comment by lionsoul2014** [comment]
组成最终格式看/data/ip.merge.txt，之前旧版本的大概流程如下：https://www.oschina.net/news/83725/ip2region-1-2-4。新版本大致一样！

**Comment by timegoby** [comment]
你好，我看了流程，但是说的很笼统
比如，IP的预分段和各分段的同步升级有没有具体的参考文档呢？
感谢！

**Comment by lionsoul2014** [comment]
升级程序和算法目前尚未开源，介于版权问题这个暂时不会开源！
