### ISSUE TITLE
.netcore BtreeSearch 返回地区乱码

### ISSUE THREAD

**Issue by tryour** [lionsoul2014/ip2region#129]
ip2region.db版本:  Upgrade the ip source data and db data to the latest version 2019/05/02
IP2Region.dll Nuget包版本：1.2.0

问题描述：
不是所有的IP查询结果都是乱码，部分IP数据是乱码，如IP：223.104.246.20
这个IP三种方法也只有BtreeSearch方法会出现乱码，其它两种都不会出现乱码:
```
using (var _search = new DbSearcher(path))
{
    Console.WriteLine(_search.BtreeSearch("223.104.246.20").Region);  // 乱码
    Console.WriteLine(_search.MemorySearch("223.104.246.20").Region); // 正常
    Console.WriteLine(_search.BinarySearch("223.104.246.20").Region); // 正常
}
```

**Comment by lionsoul2014** [comment]
@RocherKong csharp的，估计btree的实现有问题！

**Comment by RocherKong** [comment]
![image](https://user-images.githubusercontent.com/10215178/70604951-87c60480-1c34-11ea-89b3-64a6539175ed.png)
我的没问题啊

**Comment by RocherKong** [comment]
偶现还是必现？ @tryour

**Comment by tryour** [comment]
必现的，部分IP数据是只要查询就是乱码，不是所有的IP都是乱码.

**Comment by RocherKong** [comment]
@tryour 哪些ip?我用你给的ip试了ok的

**Comment by lionsoul2014** [comment]
给个建议可以排除下：不知C#是否有类似Java的maven打包工具，用maven打包的时候会更改ip2region.db里面的内容，导致加载查询的时候出问题了，设置打包工具不要去打包db文件。
