### ISSUE TITLE
请问ip.merge.txt是怎么来的？

### ISSUE THREAD

**Issue by kewang85** [lionsoul2014/ip2region#13]
请问ip.merge.txt是怎么来的？

**Comment by lionsoul2014** [comment]
https://www.oschina.net/news/83725/ip2region-1-2-4
介绍了来源，数据主要来自taobao和free ipip。

**Comment by kewang85** [comment]
taobao和free ipip有开放接口可以获取数据吗，有没有生成ip.merge.txt的代码啊

**Comment by lionsoul2014** [comment]
ip.taobao.com和free.ipip.net两个接口

数据的更新代码因为和公司的版权问题，现在没有开源
