### ISSUE TITLE
java.lang.NegativeArraySizeException，在我本地是可以的，部署到tomcat上就报NegativeArraySizeException异常

### ISSUE THREAD

**Issue by liubing67** [lionsoul2014/ip2region#135]
![image](https://user-images.githubusercontent.com/16477950/69325952-f3483200-0c85-11ea-8abd-a0dc8c2df749.png)
java.lang.NegativeArraySizeException，在我本地是可以的，部署到tomcat上就报NegativeArraySizeException异常，有没有大佬遇到过啊？

**Comment by liubing67** [comment]
![image](https://user-images.githubusercontent.com/16477950/69392015-89746a80-0d0f-11ea-80bc-55eb217e3132.png)
好像是这行报的错

**Comment by liubing67** [comment]
![image](https://user-images.githubusercontent.com/16477950/69392746-ff79d100-0d11-11ea-956f-7398e5d07e1c.png)
![image](https://user-images.githubusercontent.com/16477950/69392772-11f40a80-0d12-11ea-87cb-c93b7bcfc86b.png)

**Comment by liubing67** [comment]
这个项目部署在了tomcat 9上

**Comment by lionsoul2014** [comment]
老问题了，不要使用maven打包db文件，会改变db文件的内容。旧的issue有好几个提到了，可以看下！
