### ISSUE TITLE
Go版一直拉不下来

### ISSUE THREAD

**Issue by lamplife** [lionsoul2014/ip2region#136]
Cloning into '/go/src/github.com/lionsoul2014/ip2region'...
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
package github.com/lionsoul2014/ip2region/binding/golang: exit status 128

@mohong122  mohong122

**Comment by lionsoul2014** [comment]
这个貌似是网络问题

**Comment by lamplife** [comment]
> 这个看起来更像是网络问题

对比过，拉其它包挺稳的，等稍晚些我再试试

**Comment by lionsoul2014** [comment]
对golang不了解，等 @mohong122 来看看

**Comment by mohong122** [comment]
这个是网络不稳定，可切换一下网络试试

**Comment by lamplife** [comment]
> 这个是网络不稳定，可切换一下网络试试
今天又可以了，一下就拉下来了，可以了！
