### ISSUE TITLE
不支持IPv6，什么时候能支持IPv6？

### ISSUE THREAD

**Issue by ldqk** [lionsoul2014/ip2region#142]

**Comment by lionsoul2014** [comment]
不会支持ipv6

**Comment by amazingWu** [comment]
基于该版本开发了支持ipv6的版本，移驾 https://github.com/amazingWu/ip2region-v6

**Comment by ldqk** [comment]
> 基于该版本开发了支持ipv6的版本，移驾 https://github.com/amazingWu/ip2region-v6

仓库还是空的？
