### ISSUE TITLE
ip数据相关问题？

### ISSUE THREAD

**Issue by copyshop** [lionsoul2014/ip2region#143]
我有一个疑问 获取调用
淘宝IP地址库, http://ip.taobao.com/
GeoIP, https://geoip.com/
纯真IP库, http://www.cz88.net/

数据是从0.0.0.0 一直到255.255.255.255 这样循环 一个一个依次调用返回数据吗？   如果是这样，调用次数太多了。

**Comment by lionsoul2014** [comment]
不是这样的，这样子算下得几十年才能升级完(目前1秒钟的请求次数控制不超过5，实际不到3)。
ip2region的升级程序目前不开源，是基于历史数据的跳跃式的升级，一般一秒钟请求5次以下，几天就全部升级完了。
