### ISSUE TITLE
ip2region.db 的账号密码

### ISSUE THREAD

**Issue by Universe91** [lionsoul2014/ip2region#146]
使用navicat打开该数据库文件，账号密码多少

**Comment by lionsoul2014** [comment]
这个理解有偏差，ip2region.db文件不是任何标准的数据格式，是自创的存储格式，没有所谓的密码，用navicat等任何DBMS工具都打不开的，任何的DBMS工具都不可能这个级别的查询速度。

DB格式详情：http://dongyado.com/tool/2016/08/18/structure-of-ip2region-database-file/
