### ISSUE TITLE
db文件打到jar包查询返回null

### ISSUE THREAD

**Issue by ileeoyo** [lionsoul2014/ip2region#148]
只打算使用memory算法，把db文件打到jar包中，class static初始化时读取byte树组初始化Searcher，以后全局公用Searcher，查询ip就返回null。IDE中可以正常使用。

**Comment by lionsoul2014** [comment]
很多issue都提到过了，不要使用maven打包，或者设置打包不改变db文件的格式，不然就出问题了。

**Comment by ileeoyo** [comment]
> 改变

确实打包到resources不是好的选择，现在我已经把db放到jar包外。从个人研究的角度来说，我想问一下“设置打包不改变db文件的格式”这个怎么设置，或者给一点提示关键词？

**Comment by lionsoul2014** [comment]
查看下旧的issue，我一般不使用maven直接打包。
