### ISSUE TITLE
查询出的地市为0

### ISSUE THREAD

**Issue by weirong1113** [lionsoul2014/ip2region#149]
36.154.211.246这个ip查询出就是‘中国|0|江苏省|0|移动'，百度里这个ip对应南京。我查了下ip.merge.txt里34行ip范围对应‘中国|0|江苏省|0|移动’，请问为什么会有地市为0的

**Comment by lionsoul2014** [comment]
原始数据没有的显示的就是0，不是全部的数据都可以确保有城市的。
