### ISSUE TITLE
data目录下的ip2region.db格式被改动过吗？

### ISSUE THREAD

**Issue by chaosact** [lionsoul2014/ip2region#151]
data目录下的ip2region.db是被精简过的吧？
[根据项目下提供的原理解说](https://github.com/dongyado/dongyado.github.io/blob/master/_posts/2016-08-18-structure-of-ip2region-database-file.md)
其中描述描述的数据结构，其中index partion每块为4K，但是经测试发现。并不是完全是这样。

例1：superblock中的last index ptr为7529242，但是文件总长度只有7529288，两者差值只有46‬，根本就存放不下4096长度的index partion。

例2：superblock中的first index ptr为495130，last index ptr为7529242，两者差值为7034112，除以4096的结果为1,717.3125，并不是一个整数。

由于数据内没有存放header index实际的数量,index partion的数据也被精简过，导致无法获得或计算出header index实际的数量。bittree算法时也只能通过循环递增索引来进行计算，无法用二分法等方法优化检索速度。

**Comment by lionsoul2014** [comment]
例1: last index ptr指向的是数据末尾的地址，也就是数据存储在last index ptr的前面。
例2: 无法整除4096，ceil取整就好了。

我建议你打开代码自己去调试下，生成代码和查询代码都有，这样你就可以理解得更清楚，这些疑问也就解决了，ip2region.db文件每次发布都会进行ip.merge.txt中的全批量查询的。

**Comment by chaosact** [comment]
问题1：每个index partion大小是4K，那index partion的总长度难道不应是4K的倍数吗？

问题2：根据描述**_“HEADER INDEX 区是对 INDEX 区的二级索引，INDEX总长度除以 4K 就是 HEADER INDEX 的实际索引数”_** 。这个INDEX总长度是指superblock中的last index ptr为和first index ptr之间的差值吗？这两数的差是7034112，除以4096是1717.3125。但是HeaderIndex的最大长度也只能是1024吧，实际长度是861，我要怎么求出这个861？

**Comment by lionsoul2014** [comment]
去看marker的代码
