### ISSUE TITLE
Index pointer not found是什么问题？

### ISSUE THREAD

**Issue by linlj199** [lionsoul2014/ip2region#157]
python3在执行的时候报出Exception:Index pointer not found
if sptr ==0:raise Exception("Index pointer not found")
这是什么原因？

**Comment by lionsoul2014** [comment]
默认的python客户端都是做过测试的，描述下具体的情况，什么系统，哪个版本，有没有自定义db文件，贴下使用代码。

**Comment by wujunfeng1991** [comment]
> 默认的python客户端都是做过测试的，描述下具体的情况，什么系统，哪个版本，有没有自定义db文件，贴下使用代码。


我的报错一样。。我是放到服务端用的。每次请求做地区判断。
`def getProvinces(request):
    try:
        ip = geIP(request)
        print(ip)
        dbFile = os.path.join(os.getcwd(),"tools","ip2region.db")
        if os.path.isfile(dbFile) and os.path.exists(dbFile):
            searcher = Ip2Region(dbFile)
            data = searcher.btreeSearch(ip)
            return data["region"].decode('utf-8').split("|")[2]
    except Exception as e:
        raise e
        return None`

**Comment by wujunfeng1991** [comment]
> 默认的python客户端都是做过测试的，描述下具体的情况，什么系统，哪个版本，有没有自定义db文件，贴下使用代码。

我的问题一样的，我是放到服务端使用，每次请求过来做地区判断。
`def getProvinces(request):
    try:
        ip = geIP(request)
        print(ip)
        dbFile = os.path.join(os.getcwd(),"tools","ip2region.db")
        if os.path.isfile(dbFile) and os.path.exists(dbFile):
            searcher = Ip2Region(dbFile)
            data = searcher.btreeSearch(ip)
            return data["region"].decode('utf-8').split("|")[2]
    except Exception as e:
        raise e
        return None`

**Comment by La1tron** [comment]
> 默认的python客户端都是做过测试的，描述下具体的情况，什么系统，哪个版本，有没有自定义db文件，贴下使用代码。

当前db文件版本(2020/03/06 version e42d45b) 查询某些IP也会发生Index pointer not found错误。
出现错误的IP有:219.235.234.218,222.73.5.145,218.104.67.157,218.88.183.70,221.237.29.42,216.105.38.10,216.118.102.8,217.69.141.145,223.8.237.16,216.67.245.36,218.22.224.163,218.244.149.200,223.252.214.72,222.78.123.193,218.66.59.190,218.88.182.49,222.181.10.17,219.132.165.16,216.118.102.8,219.117.212.242,217.160.0.37,216.118.102.8,218.88.180.152,221.6.167.27,222.181.203.235,222.73.8.48,222.94.199.48

使用的系统: Debian
版本: 9.11
未使用自定义db文件

使用该段代码查询IP218.86.13.71复现错误
```
search = Ip2Region('ip2region.db')
print(search.btreeSearch('218.86.13.71'))
```

**Comment by lionsoul2014** [comment]
@La1tron 这个要关注下社区的消息，https://www.oschina.net/news/132390/ip2region-released-20210309。
最新版本的数据不要使用btree算法，关于大数据量的新的数据格式我这边再设计。
