### ISSUE TITLE
能提供php或者Python版本的db生成代码吗？

### ISSUE THREAD

**Issue by pz9042** [lionsoul2014/ip2region#158]
不会Java，能否提供一个Python或者php版本的生成代码，很想了解这种存储的规则

**Comment by lionsoul2014** [comment]
会提供C的生成代码，不会提供PHP或者Python的，存储算法可以看README中的博客地址。

**Comment by pz9042** [comment]
> 会提供C的生成代码，不会提供PHP或者Python的，存储算法可以看README中的博客地址。

C 的生成代码在哪了？文档里只说了提供Java的

**Comment by lionsoul2014** [comment]
> > 会提供C的生成代码，不会提供PHP或者Python的，存储算法可以看README中的博客地址。
> 
> C 的生成代码在哪了？文档里只说了提供Java的

会，目前还没有
