### ISSUE TITLE
结果乱码

### ISSUE THREAD

**Issue by Fcscanf** [lionsoul2014/ip2region#165]
![image](https://user-images.githubusercontent.com/27654200/92341414-3463e280-f0f0-11ea-92e3-2b32feca9923.png)

**Comment by lionsoul2014** [comment]
windows机器是这样的，很多issue提到这个问题了，把终端编码设置为UTF-8即可。

**Comment by Fcscanf** [comment]
在更新db的时候打印的也是乱码呢
![image](https://user-images.githubusercontent.com/27654200/92357833-15c71100-f11b-11ea-81b7-83880e6421c9.png)
我的终端编码一直是UTF-8呢
![image](https://user-images.githubusercontent.com/27654200/92359433-d3530380-f11d-11ea-9e5c-43f329ad71b5.png)

**Comment by lionsoul2014** [comment]
一个原因，输出编码和终端呈现的编码都设置一样就好。db生成内部编码都是utf-8，你这个只是设置java源程序的存储编码格式

**Comment by Fcscanf** [comment]
@lionsoul2014 程序里的中文字符编码正确打印，未重新编码异常情况
![image](https://user-images.githubusercontent.com/27654200/92370206-8f1b2f80-f12c-11ea-89e9-2955e94811dd.png)
但是打开数据集看到的是乱码情况
![image](https://user-images.githubusercontent.com/27654200/92370340-b96ced00-f12c-11ea-98d7-df7e3e02438d.png)
但是预览时没乱码
![image](https://user-images.githubusercontent.com/27654200/92370396-d1447100-f12c-11ea-8173-3b0b6d433483.png)
