### ISSUE TITLE
怎么将获取的region细分一下

### ISSUE THREAD

**Issue by love2wind** [lionsoul2014/ip2region#170]
怎么将获取的region细分一下，输出就像这样的格式

-- | -- | --
country | string | 国家
province | string | 省份
city | string | 城市
ISP | string | 运营商

这样的格式，比较菜不会php

**Comment by lionsoul2014** [comment]
2163|中国|华南|广东省|深圳市|鹏博士
把这个数据explode下，通过序号索引去获取即可。

**Comment by lionsoul2014** [comment]
各种语言版本都有，可以选择你会的语言。

**Comment by love2wind** [comment]
> 2163|中国|华南|广东省|深圳市|鹏博士
> 把这个数据explode下，通过序号索引去获取即可。

不会啊，大佬。小白一枚。我是用的PHP调用的。
