### ISSUE TITLE
jcenter最新版是1.7.2，但release已经到了2.2.0-release，到底哪个才是最新版？

### ISSUE THREAD

**Issue by kkmike999** [lionsoul2014/ip2region#173]
https://jcenter.bintray.com/org/lionsoul/ip2region/ 最高是1.7.2，但https://github.com/lionsoul2014/ip2region/releases发布了2.2.0，哪个才是最新版？

**Comment by lionsoul2014** [comment]
每次升级只是数据更新，maven的版本不变，1.7.2即可。
