### ISSUE TITLE
定义为全局变量问题

### ISSUE THREAD

**Issue by pathbox** [lionsoul2014/ip2region#18]
我用的是go的包

region, err := ip2region.New("ip2region.db") 这一句我觉得定义为全局变量。系统启动的时候执行一次加载到内存，之后就不需要再执行了，这样也就只消耗了2M左右的内存，效果是否是最好的？

如果每次请求都要执行一次上面的操作，相当于每次都会有一次打开文件的操作吧？当并发量非常大的时候，文件描述符打开太多，就会报 open too many file 的错误了

当我用定义成全局变量

var Region, _ = ip2region.New("ip2region.db")

在做benchmark 测试的时候， 得到了 和你的测试结果一致的结果，MemorySearch 是最快的

**Comment by lionsoul2014** [comment]
这个思路没问题的，有几个点需要注意下：
1，ip2region的查询对象并不是进程或者线程安全的。
2，btree和binary算法不支持这种全局的并发，并发使用会有问题，File的操作不支持并发！
3，memory模式的对象，如果在发布前已经调用一次初始化了，那就没问题，可以并发使用。

**Comment by pathbox** [comment]
1 我没有修改ip2region的查询对象，只是查询，所以应该不会出现线程安全问题。
2 btree binary 算法  需要这样操作吗？

```go
var region, _ = ip2region.New("ip2region.db")
defer region.CLose()
```

3 我决定使用MemorySearch方式了，我本地benchmark速度是另外两种的十倍。所以定义了全局变量的方式

关于你说的 ”在发布前已经调用一次初始化了，那就没问题，可以并发使用“。 我没有十分理解，发布前具体指的是什么？

**Comment by lionsoul2014** [comment]
发布就是你创建好的ip2region对象引用给到其他地方调用的时候。
再这之前，先调用一次查询，初始化里面的数据，之后就可以安全的用于并发了。
