### ISSUE TITLE
windows平台，c语言打印乱码

### ISSUE THREAD

**Issue by kris425** [lionsoul2014/ip2region#183]
降binding/c下面的testSearcheer.c代码改造支持windows，控制台打印出来乱码，这个db文件里面存储的数据是什么编码，我的应用程序需要怎么转码才能正确输出不乱码？

**Comment by lionsoul2014** [comment]
UTF-8，window的控制台默认是ANSI编码，调整输出编码为UTF-8，这个不影响具体项目的使用。
