### ISSUE TITLE
新的DB存在问题

### ISSUE THREAD

**Issue by keysLo** [lionsoul2014/ip2region#184]
部分IP识别为0，但是ip.merge.txt上面是包含此ip
![395EAD88-0DF4-45A6-BF3F-F07231932C84](https://user-images.githubusercontent.com/34831410/111771631-e3c31280-88e6-11eb-9e14-5626cc690f90.jpeg)

**Comment by lionsoul2014** [comment]
常用的话，关注下社区，https://www.oschina.net/news/132390/ip2region-released-20210309，这个版本的数据不要使用btree算法，存储的数据量有限。
