### ISSUE TITLE
好多查询有问题

### ISSUE THREAD

**Issue by duyanming** [lionsoul2014/ip2region#190]
![image](https://user-images.githubusercontent.com/17999146/115197964-2402f400-a124-11eb-8f2f-ab904596e944.png)
![image](https://user-images.githubusercontent.com/17999146/115197805-fd44bd80-a123-11eb-827a-bd81ebd9abc6.png)

**Comment by lionsoul2014** [comment]
数据问题，关注社区，https://www.oschina.net/news/132390/ip2region-released-20210309
