### ISSUE TITLE
新ip.merge.txt前40155行完全重复

### ISSUE THREAD

**Issue by liudinghua** [lionsoul2014/ip2region#197]
作者你好！首先非常感谢您贡献的这个项目。对我们的应用中解析ip起到了重要作用。本次查看ip库文本文件，无意中发现40156 ~ 80300 行完全和前面40155行重复。请予以审查，修正，并排查下，是否还存在其他问题。祝好~

**Comment by lionsoul2014** [comment]
新版本已解决该问题
