### ISSUE TITLE
查询结果字段能否新增一个国家代码字段？

### ISSUE THREAD

**Issue by ihotte** [lionsoul2014/ip2region#198]
查询结果字段能否新增一个国家代码字段？

---
部分场景下需要利用国家字段进行下一步操作，现在国家字段只有中文不利于后续操作

**Comment by lionsoul2014** [comment]
if country == "中国" {
    // do whatever ...
}

**Comment by ihotte** [comment]
> if country == "中国" {
> // do whatever ...
> }

200 个国家 200 个 if ？

**Comment by lionsoul2014** [comment]
> > if country == "中国" {
> > // do whatever ...
> > }
> 
> 200 个国家 200 个 if ？

200个国家难道就没有200个国家代码吗？
数据多就建议使用map映射就好
