### ISSUE TITLE
兄弟.IP库该更新了

### ISSUE THREAD

**Issue by bqf9979** [lionsoul2014/ip2region#201]
很多IP查出来已经不准确了

**Comment by xxzcool** [comment]
+1

**Comment by AlibabaDAMO** [comment]
太不准确了，现在只能先用纯真顶着了，不知道还更不更

**Comment by ldqk** [comment]
+1

**Comment by BoboYaya** [comment]
是省市不准确还是国家不准确了？目前我们只要求国家准确就可以了。后续不知道要不要更精细的。

**Comment by bqf9979** [comment]
> 
> 
> 是省市不准确还是国家不准确了？目前我们只要求国家准确就可以了。后续不知道要不要更精细的。

项目主人已放弃治疗, 用我买的还好,有需求先用我项目里的吧虽然也有的不准确

**Comment by keysLo** [comment]
> > 是省市不准确还是国家不准确了？目前我们只要求国家准确就可以了。后续不知道要不要更精细的。
> 
> 项目主人已放弃治疗, 用我买的还好,有需求先用我项目里的吧虽然也有的不准确
你好，请问下你的ip.merge.txt能提供吗？有些IP段我想自行更改

**Comment by orestonce** [comment]
> > > 是省市不准确还是国家不准确了？目前我们只要求国家准确就可以了。后续不知道要不要更精细的。
> > 
> > 
> > 项目主人已放弃治疗, 用我买的还好,有需求先用我项目里的吧虽然也有的不准确
> 
> 大兄弟，首先感谢一下。能否同步更新一下ip.merge.txt，因为项目已经运行的原因，现有的db库增加了洲的信息。想通过ip.merge.txt编一份不带洲信息的db库。还有您frok的项目没有issue揩油开放。

我创建了一个文件转换工具，可以让db文件和txt文件相互转换，自取: https://github.com/orestonce/Ip2regionTool

**Comment by seven08x** [comment]
> > > > 是省市不准确还是国家不准确了？目前我们只要求国家准确就可以了。后续不知道要不要更精细的。
> > > 
> > > 
> > > 项目主人已放弃治疗, 用我买的还好,有需求先用我项目里的吧虽然也有的不准确
> > 
> > 
> > 大兄弟，首先感谢一下。能否同步更新一下ip.merge.txt，因为项目已经运行的原因，现有的db库增加了洲的信息。想通过ip.merge.txt编一份不带洲信息的db库。还有您frok的项目没有issue揩油开放。
> 
> 我创建了一个文件转换工具，可以让db文件和txt文件相互转换，自取: https://github.com/orestonce/Ip2regionTool

不行啊 转换失败了  显示没有完全聚合

**Comment by orestonce** [comment]
@wuhua08 没有全部聚合的意思是相邻的两段ip的后续的附加信息是一样的。可以检查提示的相邻信息，然后将这两段合成一段即可

**Comment by orestonce** [comment]
@wuhua08  删除了“没有全部聚合” 的检查，可以再试试 https://github.com/orestonce/Ip2regionTool/releases/tag/v1.0

**Comment by wuhua08** [comment]
> @wuhua08 删除了“没有全部聚合” 的检查，可以再试试 https://github.com/orestonce/Ip2regionTool/releases/tag/v1.0

转出来了 谢了老哥

**Comment by geekworm-com** [comment]
> > > > 是省市不准确还是国家不准确了？目前我们只要求国家准确就可以了。后续不知道要不要更精细的。
> > > 
> > > 
> > > 项目主人已放弃治疗, 用我买的还好,有需求先用我项目里的吧虽然也有的不准确
> > 
> > 
> > 大兄弟，首先感谢一下。能否同步更新一下ip.merge.txt，因为项目已经运行的原因，现有的db库增加了洲的信息。想通过ip.merge.txt编一份不带洲信息的db库。还有您frok的项目没有issue揩油开放。
> 
> 我创建了一个文件转换工具，可以让db文件和txt文件相互转换，自取: https://github.com/orestonce/Ip2regionTool

我先fork了，，，多谢

**Comment by schonglin** [comment]
@bqf9979 新版本的数据怎么格式变了啊
比如原来的返回是 ：{"cityId":2261,"dataPtr":402681,"region":"中国|0|广东省|深圳市|移动"}
改成新得数据库返回：{"cityId":0,"dataPtr":648720,"region":"中国|亚洲|广东|深圳|移动/基站WiFi"}
没有省 和市 返回了 ~

**Comment by holycd** [comment]
> > 是省市不准确还是国家不准确了？目前我们只要求国家准确就可以了。后续不知道要不要更精细的。
> 
> 项目主人已放弃治疗, 用我买的还好,有需求先用我项目里的吧虽然也有的不准确



> > 是省市不准确还是国家不准确了？目前我们只要求国家准确就可以了。后续不知道要不要更精细的。
> 
> 项目主人已放弃治疗, 用我买的还好,有需求先用我项目里的吧虽然也有的不准确

我用你的db直接替换原项目db文件，直接报异常，是有什么地方需要修改的吗

**Comment by devin87** [comment]
> > 是省市不准确还是国家不准确了？目前我们只要求国家准确就可以了。后续不知道要不要更精细的。
> 
> 项目主人已放弃治疗, 用我买的还好,有需求先用我项目里的吧虽然也有的不准确

感谢大佬更新ip数据，但20210309这版数据存在40155行重复的数据，会导致生成的 ip2region.db 文件较大，能否去掉重复数据，如果能同步更新 ip.merge.txt 就更好了
