### ISSUE TITLE
升级后返回的地名变了（广东省,深圳市->广东,深圳）

### ISSUE THREAD

**Issue by hesimin** [lionsoul2014/ip2region#205]
升级后返回的地名变了，和原来返回的名字不一致，业务数据查询的时候就不统一了
旧库：101.105.35.57 =》[中国, 0, 广东省, 深圳市, 鹏博士]
升级到新库后：101.105.35.57 =》[中国, 0, 广东, 深圳, 鹏博士]

**Comment by uuidcoder** [comment]
大佬 有什么解决方案吗  我现在也是遇到这个问题

**Comment by hesimin** [comment]
好像已经修复了
