### ISSUE TITLE
增加 C/C++ Windows 示例

### ISSUE THREAD

**Issue by SourcePowered** [lionsoul2014/ip2region#21]
抱歉，能否增加 Windows 下的 C/C++ 示例，这对于菜鸟来说很有帮助。谢谢！

**Comment by lionsoul2014** [comment]
binding/c/testSearcher.c是c的测试用例。
基于内核基于ANSI C写的，windows下也可以运行

测试代码，去掉sys/time和时间相关的代码，即可在windows下编译运行
