### ISSUE TITLE
配置了JVM堆栈参数就报Java heap space

### ISSUE THREAD

**Issue by 18682411831** [lionsoul2014/ip2region#216]
配置了这个参数。加到2048M还是报错
![image](https://user-images.githubusercontent.com/35253015/159667298-655a7531-e0d1-4535-9356-b09c846a5314.png)

![image](https://user-images.githubusercontent.com/35253015/159667141-a46daef7-f5a4-49ae-a6b3-bfc197e19ca8.png)

发现报错(DataBlock) method.invoke(searcher, ip); 就会报Caused by: java.lang.OutOfMemoryError: Java heap space
然后我把-Xms -xmx 调大一倍
![image](https://user-images.githubusercontent.com/35253015/159667748-bd868fe9-c251-415c-b149-a38897b1628d.png)
结果还是报错
![image](https://user-images.githubusercontent.com/35253015/159667968-16f762dc-9521-46a3-93a5-919223c71c07.png)

**Comment by 18682411831** [comment]
需要多大的内存。这个方法

**Comment by lionsoul2014** [comment]
估计你走进误区，不用设置JVM，默认就可以跑，内存占用很小。是不是用法导致死循环调用了？或者是如果你有自定义生成数据，确认下生成的db文件是否有问题。

**Comment by 18682411831** [comment]
> 估计你走进误区，不用设置JVM，默认就可以跑，内存占用很小。是不是用法导致死循环调用了？或者是如果你有自定义生成数据，确认下生成的db文件是否有问题。

db文件没问题，不设置jvm确实是可以跑。但是在容器里，上生产环境。需要做内存限制。一配置jvm就报错。

**Comment by 18682411831** [comment]
` /**
     * 根据IP获取城市信息
     * @param ip
     * @return
     */
    public static String getCityInfo(String ip) {
        return getCityInfo(ip, DbSearcher.BTREE_ALGORITHM);
    }

    public static String getCityInfo(String ip, Integer algorithm) {
        if (Util.isIpAddress(ip) == false) {
            return Strings.EMPTY;
        }

        if (LOCAL_IP.equals(ip)) {
            return "本地访问";
        }

        String dbPath = IPUtils.class.getResource("/ip2region.db").getPath();
        File file = new File(dbPath);

        // 打成jar包时，ip2region.db文件路径发生变化，导致File无法读取，通过stream流方式复制生成临时的ip2region.db文件

        if (file.exists() == false) {
            String tmpdir = System.getProperties().getProperty("java.io.tmpdir");
            dbPath = tmpdir + "/ip2region.db";
            file = new File(dbPath);
            if (file.exists() == false) {
                try {
                    FileUtils.copyInputStreamToFile(IPUtils.class.getClassLoader()
                            .getResourceAsStream("classpath:ip2region.db"), file);
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        }
        try {
            DbConfig config = new DbConfig();
            DbSearcher searcher = new DbSearcher(config, dbPath);
            Method method;
            switch (algorithm) {
                case DbSearcher.BTREE_ALGORITHM:
                    method = searcher.getClass().getMethod("btreeSearch", String.class);
                    break;
                case DbSearcher.BINARY_ALGORITHM:
                    method = searcher.getClass().getMethod("binarySearch", String.class);
                    break;
                case DbSearcher.MEMORY_ALGORITYM:
                    method = searcher.getClass().getMethod("memorySearch", String.class);
                    break;
                default:
                    method = searcher.getClass().getMethod("memorySearch", String.class);
                    break;
            }
            DataBlock dataBlock = (DataBlock) method.invoke(searcher, ip);
            searcher.close();
            return dataBlock.getRegion();

        } catch (Exception e) {
            e.printStackTrace();
        }
        return Strings.EMPTY;
    }`

**Comment by lionsoul2014** [comment]
我总觉的这个和ip2region无关，我不知道怎么回答你的问题，实际内存占用很少。会不会是线上请求数比较多，用的memory算法，导致内存暴涨？
btree算法最新版本的数据不要用，binary算法内存一次请求内存占用是kb以下的。memory算法需要把对象全局话，不然确实会占据很多内存。

**Comment by 18682411831** [comment]
> 我总觉的这个和ip2region无关，我不知道怎么回答你的问题，实际内存占用很少。会不会是线上请求数比较多，用的memory算法，导致内存暴涨？ btree算法最新版本的数据不要用，binary算法内存一次请求内存占用是kb以下的。memory算法需要把对象全局话，不然确实会占据很多内存。

我测试的这个方法，都没有任何操作。就说直接获取IP地址然后获取归宿地。不配置jvm就能成功，配置了就报内存溢出。

**Comment by 18682411831** [comment]
我在本地 也复现了。这个问题。跟环境没啥关系啊。。。

**Comment by Jijun** [comment]
我在用Java生成xdb的时候，遇到相同的问题，发现是loadSegments全部读入内存，导致crash
