### ISSUE TITLE
lua_c的查询并发低耗时高是什么原因

### ISSUE THREAD

**Issue by holycd** [lionsoul2014/ip2region#218]
测试代码如下，结果 0|中国|0|浙江|杭州|电信 in 10.000000 millseconds 有时又是0 millseconds

package.cpath = package.cpath ..';/usr/local/src/ip2region-20210309-release/binding/lua_c/Ip2region.so';

local Ip2region = require "Ip2region";
local ip2region = Ip2region.new("ip2region.db");
local line=ngx.var.remote_addr

local data;
local s_time = os.clock();
data = ip2region:memorySearch(line);

local cost_time = (os.clock() - s_time) * 1000; -- to millseconds
if ( data == nil ) then
         ngx.say("Failed for ip="..line.." is it a valid ip address ?");
    else
         ngx.say(string.format("%u|%s in %5f millseconds\n", data.city_id, data.region, cost_time));
end

ip2region:close();
~

**Comment by lionsoul2014** [comment]
这个 memory 查询要持久化，不然每次都要加载db文件，data这个对象持久化，伴随nginx服务启动，然后以全局的形式提供服务。

**Comment by holycd** [comment]
嗯，已经解决，之前使用的姿势不对，nginx+lua_c+LuaJIT 2.1.0版本已经测试成功，速度杠杠的，就是nginx的cpu的使用率会随着并发高而很高。
