### ISSUE TITLE
疑问：关于2.0版本的IPv6支持

### ISSUE THREAD

**Issue by DreamOfIce** [lionsoul2014/ip2region#228]
请问大佬，2.0的xdb格式支持ipv6吗？
自带的数据库似乎没有IPv6，数据库可以添加IPv6记录吗

**Comment by lionsoul2014** [comment]
不支持，ipv6主要是没有数据，数据库倒是可以设计的，这个和v4的思路也会不一样。

**Comment by DreamOfIce** [comment]
> 不支持，ipv6主要是没有数据，数据库倒是可以设计的，这个和v4的思路也会不一样。
感谢解答！
呃，那我自己去设计一个吧o_o ....

**Comment by lionsoul2014** [comment]
Ip2region 3.0 发布 - XDB 目前已正式的提供了 IPv6 的支持，Golang 版本已经实现了，其他语言会陆续上线，详情请参考：
https://www.oschina.net/news/370887/ip2region-3-0-0-release-with-ipv6-supported

./data/ 下提供了一份 原始的 1.8G+ 的 ipv6_source.txt 和 一份生成好的 ip2region_v6.xdb 文件，参考 [Golang Binding](https://github.com/lionsoul2014/ip2region/tree/master/binding/golang) 文档进行使用。
