### ISSUE TITLE
提个建议,一些现成的免费IP库

### ISSUE THREAD

**Issue by DreamOfIce** [lionsoul2014/ip2region#229]
这些都可以下载CSV格式,比起大量调用某些API可能会方便一些
[Maxmind-GeoLite](https://dev.maxmind.com/geoip/geolite2-free-geolocation-data?lang=en)
[DB-IP](https://db-ip.com/db/lite.php) 无需注册账号
[IP2Location](https://lite.ip2location.com/ip2location-lite)

**Comment by lionsoul2014** [comment]
如果你可以拿到这些数据，可以直接用他们的或者利用ip2region来帮你管理这些数据，ip2region本身没有数据，也不是重点。

**Comment by lionsoul2014** [comment]
重点是xdb的数据引擎，以及不同语言实现和周边工具给开发带来的便利，我并不像重复造这些成本很高的轮子。

**Comment by lionsoul2014** [comment]
例如：可以提供从 maxmind/GeoIP等平台导入免费标准化数据的工具，给有需要的人多一个选择，不会再去基于这些平台做数据整合。

**Comment by DreamOfIce** [comment]
> 如果你可以拿到这些数据，可以直接用他们的或者利用ip2region来帮你管理这些数据，ip2region本身没有数据，也不是重点。

是的，我也清楚IP2region核心是格式与算法。
只是说可以拿这些数据生成仓库默认的演示数据库，也许更方便一些？
