### ISSUE TITLE
自己通过jar生成ip2region.db文件后通过代码查询出来中文是乱码

### ISSUE THREAD

**Issue by timestatic** [lionsoul2014/ip2region#23]
如题,在Linux环境下也是这样,是要指定参数吗

**Comment by timestatic** [comment]
DBMark里面的 RandomAccessFile.write(byte b[])按照系统默认编码进行写入, 应该是跟这个有关系...  在Linux上设置系统编码utf-8, $ locale  检查一下......

**Comment by edgeidea** [comment]
我的mac生成db文件没问题，估计是你的系统编码设计引起的 @timestatic

**Comment by lionsoul2014** [comment]
ip2region.db需要强制使用utf-8编码，默认就是在linux下生成的。
查询乱码，有可能是你的输出解码不是UTF-8，例如：windows的ANSI编码。
