### ISSUE TITLE
spring boot集成，db放在resource下，打jar包后可以加载资源，但search不生效。本地debug生效

### ISSUE THREAD

**Issue by crazyer** [lionsoul2014/ip2region#244]

**Comment by crazyer** [comment]
本地debug结果：
<img width="741" alt="image" src="https://user-images.githubusercontent.com/6138444/180214646-e516b8c2-7c39-4b27-a076-79bc0614153f.png">
打jar包后结果：（db确认已经加载进来，只是search时候返回null）
<img width="613" alt="image" src="https://user-images.githubusercontent.com/6138444/180214787-8c5c10df-90b8-48c3-8860-3cf691b93921.png">
但如果把db文件放在jar包同级目录下，又是正常的。

**Comment by gaoyanyang** [comment]
jar包内的文件只能通过流的方式读取 可以通过如下方式读取


            DbConfig config = new DbConfig();
            InputStream resourceAsStream = Test.class.getResourceAsStream("/ip2region.db");

            byte[] bytes = new byte[resourceAsStream.available()];
            int offset = 0;
            int numRead = 0;
            while (offset < bytes.length
                    && (numRead = resourceAsStream.read(bytes, offset, bytes.length - offset)) >= 0) {
                offset += numRead;
            }
            
            System.out.println(bytes[0] +" " + bytes.length);
            DbSearcher searcher = new DbSearcher(config, bytes);
