### ISSUE TITLE
如何自己更新IP段

### ISSUE THREAD

**Issue by dianming** [lionsoul2014/ip2region#259]
failed running genDb: java.lang.Exception: discontinuous data segment: last.eip+1(612696064) != seg.sip(612699135, 36.133.0.0)
![image](https://user-images.githubusercontent.com/7877823/190388922-32297466-d9f0-42dc-ae08-37f7889fdf7c.png)
自己添加了一部分 报错了；我应该怎么添加？

**Comment by orestonce** [comment]
和前面的重叠了吧，需要每条记录不重叠。

**Comment by lionsoul2014** [comment]
参考 ReadMe 视频
