### ISSUE TITLE
IP地址段存在包含的问题

### ISSUE THREAD

**Issue by edgeidea** [lionsoul2014/ip2region#26]
11.8.0.0|11.11.255.255|中国|XX|YY|0|0
11.8.32.58|11.8.32.58|中国|XX|YY|Z|0
11.8.33.15|11.8.33.15|中国|XX|Z2|0|0

以上三个IP地址段，第一个IP包含了后面的两个。
但是查询11.9.11.1是查询不到，python返回N2

**Comment by lionsoul2014** [comment]
是最新版本的数据吗？
旧版本的数据可能存在这个问题，因为之前的升级程序有问题，最新版本的数据没有这个问题。

以下是我的查询结果：
```
ip2region>> 11.9.11.1
166|美国|0|0|0|0 in 0.04297 millseconds
```

不过发现python binding查询确实有问题！

**Comment by edgeidea** [comment]
db数据库是我自己用你的jar包生成的，就这三条IP数据。
最新1.4版本python只能查询11.8.32.58和11.8.33.15，11.9.11.1是查不到的，按理说这个IP是在11.8.0.0|11.11.255.255的范围内。

**Comment by lionsoul2014** [comment]
ip范围不能有重叠，而且最好是前后相连的，可以把重复部分拆分下！
内部用的二分检索，重叠了不知道会终止在哪个点。
