### ISSUE TITLE
Java jar包环境下，searcher无法搜索

### ISSUE THREAD

**Issue by Zelexshow** [lionsoul2014/ip2region#279]
**版本情况**
ip2region 版本2.6.6
jdk版本17.0.5

**问题描述**
工程代码环境下能够查询解析
打包成jar之后，通过debug发现，searcher能够初始化，但是执行search函数，返回null
![c27a0a0bab3b48f4a5c736d55b01d01](https://user-images.githubusercontent.com/52685431/210783388-052a9151-1f41-4d28-b0aa-522df39c442b.jpg)

**代码细节**
![image](https://user-images.githubusercontent.com/52685431/210783633-45a9516a-7595-4822-9e38-e81b6302afe0.png)
![image](https://user-images.githubusercontent.com/52685431/210783700-ed811f4c-03dc-48cd-8a04-f8321449cb96.png)

**Comment by Mr-Lei-Xuesong** [comment]
哥们，我也被这个坑了一下午
最终在mica-ip2region官方文档才发现要在pom.xml文件中要加入这个
```xml
<plugin>
    <artifactId>maven-resources-plugin</artifactId>
    <configuration>
        <nonFilteredFileExtensions>
            <nonFilteredFileExtension>db</nonFilteredFileExtension>
        </nonFilteredFileExtensions>
    </configuration>
</plugin>
```
是因为maven resources 拷贝文件是默认会做 filter，会导致我们的文件发生变化，导致不能读

**Comment by Mr-Lei-Xuesong** [comment]
哥们，我也被这个坑了一下午
最终在mica-ip2region官方文档才发现要在pom.xml文件中要加入这个
```xml
<plugin>
    <artifactId>maven-resources-plugin</artifactId>
    <configuration>
        <nonFilteredFileExtensions>
            <nonFilteredFileExtension>xdb</nonFilteredFileExtension>
        </nonFilteredFileExtensions>
    </configuration>
</plugin>
```
是因为maven resources 拷贝文件是默认会做 filter，会导致我们的文件发生变化，导致不能读

**Comment by Zelexshow** [comment]
@Mr-Lei-Xuesong 谢谢解答~
当时debug发现的情况，是这个read方法读取的buff会出现残缺，导致匹配失败：

我这边的解决方案：
使用Searcher **buffer的构造器**，解决了通过path构造出现残缺的问题：
![image](https://user-images.githubusercontent.com/52685431/211177083-352b3412-210c-4996-a79a-e827d9ee8ebf.png)
