### ISSUE TITLE
数据生成部分python模块数据异常抛出

### ISSUE THREAD

**Issue by zhangjiahuang** [lionsoul2014/ip2region#284]
原始IP数据ip.merge.txt出现错误时，现在的python数据生成模块是用logging.error记录的，程序不会停止，但由于log记录太多不利于排查原始ip数据的错误。是否可以采用异常抛出方式，将程序停止在出错的位置，这样更有利于排查错误。修改样例如下：
`# Check the continuity of data segment
            if last is not None:
                if last.end_ip + 1 != segment.start_ip:
                    logging.error(
                        "discontinuous data segment: last.eip+1({})!=seg.sip({}, {})".format(
                            sip, eip, ps[0]
                        )
                    )
                    raise ValueError("discontinuous data segment: last.eip+1({})!=seg.sip({}, {})".format(
                            sip, eip, ps[0]))`
效果如图：
![屏幕截图 2023-01-30 221226](https://user-images.githubusercontent.com/87102677/215500688-65531115-ce26-4b4e-a5bb-320d1bf3e3ff.png)
@leolin49

**Comment by leolin49** [comment]
已修改 #286
