### ISSUE TITLE
java bench时报错failed search

### ISSUE THREAD

**Issue by libailin** [lionsoul2014/ip2region#287]
在做java bench测试时报错如下，从xdb文件里获取到的是 ”俄罗斯|克 “ ，获取出来的信息不完整, 这个是什么原因呢？如何解决。最后竖线一位是isp运营商信息，是因为单条记录超长了吗？

报错信息如下：

failed search(193.150.116.0) with (俄罗斯|克 != 俄罗斯|克拉斯诺亚尔斯克边疆区|克拉斯诺亚尔斯克|Federal State Budgetary Educational Institution of Higher Education Krasnoyarsk State Medical University named after Professor V.F. Voino-Yasenetsky of the Ministry of Health of the Russian Federation)

原始数据如下：

```
193.150.116.0|193.150.116.255|俄罗斯|克拉斯诺亚尔斯克边疆区|克拉斯诺亚尔斯克|Federal State Budgetary Educational Institution of Higher Education Krasnoyarsk State Medical University named after Professor V.F. Voino-Yasenetsky of the Ministry of Health of the Russian Federation

```

**Comment by lionsoul2014** [comment]
> 个人建议 ，这种的超常的辅助信息， 拿个主键 来代表这种他，再通过主键进行匹配。。。
@libailin 
地域信息在 xdb 里面存储本身就是存储的索引地址的，相同的信息只会存储一次， 不过如果这个很长的 ISP 数据出现很多次，建议可以使用 1/2/3 等标志代替，然后应用层二次获取。

**Comment by lionsoul2014** [comment]
getInt2 实现的 bug，已经修复，用最新的 master 代码即可，2.7.0 版本在发布中
