### ISSUE TITLE
大佬，可以更新香港的ip区间段吗，万分感谢

### ISSUE THREAD

**Issue by flowerfire666** [lionsoul2014/ip2region#291]
发现有些香港的ip是显示亚太地区

**Comment by flowerfire666** [comment]
![fd4e79ee4f41c13976b25898292f0a5](https://user-images.githubusercontent.com/70675308/219305356-a52aaef4-c5c9-429b-a565-de8298d7376e.png)
大概是这几个区间段的

**Comment by flowerfire666** [comment]
![fd4e79ee4f41c13976b25898292f0a5](https://user-images.githubusercontent.com/70675308/219306336-59c7a99a-7a85-4a3c-8a19-9678c4fcd841.png)
大概是这几个区间段

**Comment by yifei245** [comment]
香港ip段基本都有问题，如
193.134.210.59
18.162.43.206

**Comment by lionsoul2014** [comment]
参考文档自己更新
