### ISSUE TITLE
高并发下，这一行出现竞争问题。

### ISSUE THREAD

**Issue by hyqc** [lionsoul2014/ip2region#293]
https://github.com/lionsoul2014/ip2region/blob/05840c74e63c5425fa96a4607562eedbc17bdfd1/v1.0/binding/golang/ip2region/ip2Region.go#L96
复现方法：

func TestA(t *testing.T) {
    reg,err := ip2region.New("./xxx.db")
   if err != nil {
      return
   }
   
  go func(){
    reg.MemorySearch("127.0.0.1")
  }
  
   go func(){
    reg.MemorySearch("127.0.0.1")
  }

   go func(){
    reg.MemorySearch("127.0.0.1")
  }

  time.Sleep(3 * time.Second)
}

执行 go test -race xx.go

建议将 MemorySearch 中读取文件内容部分放在 New 方法中

**Comment by lionsoul2014** [comment]
v1.0版本已经废弃，转用 xdb 新版本
