### ISSUE TITLE
golnag runtime error: slice bounds out of range [227016:0]

### ISSUE THREAD

**Issue by zhangwen0510** [lionsoul2014/ip2region#295]
/Users/iverson/go/pkg/mod/github.com/lionsoul2014/ip2region/binding/golang@v0.0.0-20221017063954-c5c24655eb63/xdb/searcher.go:165

runtime error: slice bounds out of range [227016:0]

**Comment by lionsoul2014** [comment]
下载仓库的 xdb，xdb文件被破坏了就会这样
