### ISSUE TITLE
大佬，给贴一个友情链接吧: Ip2regionTool 是一个使用Qt和go实现的ip2region数据转换工具

### ISSUE THREAD

**Issue by orestonce** [lionsoul2014/ip2region#298]
* https://github.com/orestonce/Ip2regionTool 
* 支持v1.0版本、v2.0版本的txt <-> db 互相转换
* 提供windows下的图形界面、命令行
* 提供 linux/darwin下的命令行

**Comment by orestonce** [comment]
可以用来辅助更新db文件，或者导出别人的db文件的数据

**Comment by lionsoul2014** [comment]
已贴
