### ISSUE TITLE
是否支持Ipv6的查询？

### ISSUE THREAD

**Issue by highfei2011** [lionsoul2014/ip2region#30]
@lionsoul2014 请问这个版本是否支持ipv6查询呢？谢谢！

**Comment by lionsoul2014** [comment]
目前只支持ipv4的。

**Comment by highfei2011** [comment]
@lionsoul2014 多谢。

**Comment by highfei2011** [comment]
@lionsoul2014 我已经实现了Ipv6的查找,[https://github.com/highfei2011/ip-radix-tree](https://github.com/highfei2011/ip-radix-tree)
