### ISSUE TITLE
[IP 地理定位数据库报告更正]！180.87.170.0/24 IP段的数据需要更新

### ISSUE THREAD

**Issue by Yxc-123** [lionsoul2014/ip2region#302]
你好

当前'180.87.170.0/24'IP段地理位置数据不准确，正确地理定位为“Singapore”。

烦请帮忙更新下，谢谢。

**Comment by lionsoul2014** [comment]
仔细阅读 ReadMe，按照稳定自己更新下

**Comment by Yxc-123** [comment]
> 仔详细阅读ReadMe，点击文档自己更新下
当然，我可以尝试修改我的终端IP库以解决问题。然而许多用户仍会从 Github 下载现有的 IP 库。考虑到这些用户可能会发现 IP 库存在问题，我们是否可以在 Github 仓库中的原始文件上进行一些更改呢？

**Comment by lionsoul2014** [comment]
> > 仔详细阅读ReadMe，点击文档自己更新下
> > 当然，我可以尝试修改我的终端IP库以解决问题。然而许多用户仍会从 Github 下载现有的 IP 库。考虑到这些用户可能会发现 IP 库存在问题，我们是否可以在 Github 仓库中的原始文件上进行一些更改呢？

你可以按照 ip.merge.txt 的格式提供详细的数据，我这边贴上一个标签，我会不定期的将这些数据同步到主仓库

**Comment by lionsoul2014** [comment]
类似于这样：https://github.com/lionsoul2014/ip2region/issues/243

**Comment by Yxc-123** [comment]
> > > 仔详细阅读ReadMe，点击文档自己更新当然
> > > 可以，我可以尝试修改我的最终IP库以解决问题。然而许多用户仍然会从Github下载现有的IP库。考虑到这些用户可能会发现IP库存在于问题中，我们是否可以在Github库中的原始文件上进行一些修改呢？
> 
> 你可以选择ip.merge.txt 的格式提供详细的数据，我这边贴上一个标签，我会把这些数据同步到仓库
感谢同步，详细信息如下：
180.87.170.0|180.87.170.255|新加坡|0|0|0|Tata
