### ISSUE TITLE
为什么同样的代码windows可以查询到省市，linux下查询不到呀？

### ISSUE THREAD

**Issue by jenkenies** [lionsoul2014/ip2region#304]
IpLocation location = new IpLocation();
        location.setIp(ip);
        try (InputStream inputStream = IPUtil.class.getResourceAsStream("/ipdb/ip2region.xdb");) {
            
            byte[] bytes = IoUtil.readBytes(inputStream);
            Searcher searcher = Searcher.newWithBuffer(bytes);
            String region = searcher.search(ip);
            log.info("testRegion---------------------------------------------------------{}:", region);
            if (StrUtil.isAllNotBlank(region)) {
                // xdb返回格式 国家|区域|省份|城市|ISP，
                // 只有中国的数据绝大部分精确到了城市，其他国家部分数据只能定位到国家，后前的选项全部是0
                String[] result = region.split("\\|");
                location.setCountry("0".equals(result[0])?StrUtil.EMPTY:result[0]);
                location.setProvince("0".equals(result[2])?StrUtil.EMPTY:result[2]);
                location.setCity("0".equals(result[3])?StrUtil.EMPTY:result[3]);
                location.setIsp("0".equals(result[4])?StrUtil.EMPTY:result[4]);
            }
            searcher.close();
        } catch (Exception e) {
            log.error("ip地址解析异常,error:{}",e);
            return location;
        }
        return location;

**Comment by JayShen1943** [comment]
我也遇到了，请问解决了吗

**Comment by JayShen1943** [comment]
> 

我已解决，改成流文件即可
