### ISSUE TITLE
Please ship IP2Region.Net lite package without integrated XDB file

### ISSUE THREAD

**Issue by EdiWang** [lionsoul2014/ip2region#309]
Current [IP2Region.Net](https://www.nuget.org/packages/IP2Region.Net) nuget package for C# contains XDB file, which makes it size over 10MB. 

In some cases, users would like to use their own database file. Although current package can support pass a custom db path to `Searcher`, it will still produce the built in XDB file in the build directory.

I suggest to ship a **IP2Region.Net.Lite** package that doesn't include XDB database file inside. So that users can have a much smaller package reference.

CC: @malus2077

**Comment by malus2077** [comment]
@EdiWang Thanks for the feedback, I'll make it happen in the near future

**Comment by malus2077** [comment]
@EdiWang   All things considered, the latest [IP2Region.Net](https://www.nuget.org/packages/IP2Region.Net) removes the included xdb file, see the [changelog](https://github.com/malus2077/ip2region/blob/master/binding/csharp/IP2Region.Net/CHANGELOG.md) for details.

**Comment by EdiWang** [comment]
Thanks @malus2077
