### ISSUE TITLE
第一次使用，请教下两个问题？

### ISSUE THREAD

**Issue by zhangwei900808** [lionsoul2014/ip2region#317]
1、xdb和db有啥区别，我应该使用哪个？
2、我可以使用网络文件路径加载db或者xdb吗？

**Comment by lionsoul2014** [comment]
db废弃了，用 xdb，可以使用网络加载 xdb

**Comment by zhangwei900808** [comment]
@lionsoul2014 多谢大佬的回答，辛苦了，有没有示例代码啊，还有个问题，每次都请求.xdb接口请求就很慢，有没有只用下载一次，后面就使用这个.xdb文件了，是不是性能更好点

**Comment by zhangwei900808** [comment]
@lionsoul2014 我将文件下载到resource/ipdb/ip2region.xdb中，获取也成功了，
```
File file = ResourceUtils.getFile("classpath:ipdb/ip2region.xdb");
        String dbPath = file.getPath();
        Searcher searcher = null;
        try {
            searcher = Searcher.newWithFileOnly(dbPath);
        } catch (IOException e) {
            logger.info("searchIpAddr exception={}", e.getMessage());
        }
```
但是，打包成docker镜像，发布到k8s之后就报错：
```
2023-08-29T07:53:50.323Z  INFO 1 --- [or-http-epoll-2] c.s.u.controller.AccountController       : --- login=class path resource [ipdb/ip2region.xdb] cannot be resolved to absolute file path because it does not reside in the file system: jar:file:/usr/local/users-service/app.jar!/BOOT-INF/classes!/ipdb/ip2region.xdb ---
```
我该如何处理呢？给个思路也行

**Comment by ZJM6658** [comment]
> @lionsoul2014 我将文件下载到resource/ipdb/ip2region.xdb中，获取也成功了，
> 
> ```
> File file = ResourceUtils.getFile("classpath:ipdb/ip2region.xdb");
>         String dbPath = file.getPath();
>         Searcher searcher = null;
>         try {
>             searcher = Searcher.newWithFileOnly(dbPath);
>         } catch (IOException e) {
>             logger.info("searchIpAddr exception={}", e.getMessage());
>         }
> ```
> 
> 但是，打包成docker镜像，发布到k8s之后就报错：
> 
> ```
> 2023-08-29T07:53:50.323Z  INFO 1 --- [or-http-epoll-2] c.s.u.controller.AccountController       : --- login=class path resource [ipdb/ip2region.xdb] cannot be resolved to absolute file path because it does not reside in the file system: jar:file:/usr/local/users-service/app.jar!/BOOT-INF/classes!/ipdb/ip2region.xdb ---
> ```
> 
> 我该如何处理呢？给个思路也行

看这个错误明显是文件加载的问题，要么放到外面机器上，要么cpr读取后使用

**Comment by zhangwei900808** [comment]
<img width="488" alt="image" src="https://github.com/lionsoul2014/ip2region/assets/4385154/293296fb-dbbf-4ffb-9a13-1d28a5ab6fca">
```
try {
            InputStream fileStream = new ClassPathResource("ipdb/ip2region.xdb").getInputStream();
            searcher = Searcher.newWithBuffer(toByteArray(fileStream));
        } catch (IOException e) {
            logger.info("searchIpAddr exception={}", e.getMessage());
//            System.out.printf("failed to create searcher with `%s`: %s\n", dbPath, e);
            return ResponseEntity.ok(new ResultSuccess<>(null));
        }
```
换成上面代码就ok了，非常感谢！
