### ISSUE TITLE
bench测试由于中文编码问题不通过

### ISSUE THREAD

**Issue by remriver** [lionsoul2014/ip2region#318]
系统：window 
语言：java
版本：2.7.0
重现步骤：执行bench测试，输入如下命令：java -jar target/ip2region-2.7.0.jar bench --db=../../data/ip2region.xdb --src=../../data/ip.merge.txt，界面提示：
failed search(0.0.0.0) with (0|0|0|内网IP|内网IP != 0|0|0|鍐呯綉IP|鍐呯綉IP)
问题原因：bench测试中读取文本文件使用系统默认编码（gbk），与文件本身编码（utf8）不一致。
错误文件：org.lionsoul.ip2region.SearchTest.java

**Comment by lionsoul2014** [comment]
Reader已经默认指定输入编码为 UTF_8 了
