### ISSUE TITLE
是否支持ipv6

### ISSUE THREAD

**Issue by wnygqg** [lionsoul2014/ip2region#32]
请问是否支持ipv6

**Comment by lionsoul2014** [comment]
Ip2region 3.0 发布 - XDB 目前已正式的提供了 IPv6 的支持，Golang 版本已经实现了，其他语言会陆续上线，详情请参考：
https://www.oschina.net/news/370887/ip2region-3-0-0-release-with-ipv6-supported

./data/ 下提供了一份 原始的 1.8G+ 的 ipv6_source.txt 和 一份生成好的 ip2region_v6.xdb 文件，参考 [Golang Binding](https://github.com/lionsoul2014/ip2region/tree/master/binding/golang) 文档进行使用。
