### ISSUE TITLE
希望CSharp打包时不要将CHANGELOG.md打包进去

### ISSUE THREAD

**Issue by zhaifanhua** [lionsoul2014/ip2region#320]
希望CSharp打包时不要将CHANGELOG.md打包进去，会影响项目目录：
![image](https://github.com/lionsoul2014/ip2region/assets/106963561/7b786e9c-c64b-4b3a-b8f8-5d0e31d0ed31)

**Comment by malus2077** [comment]
Please upgrade to version 2.0.2, thanks for the feedback!
