### ISSUE TITLE
希望能更换HttpServlet相关的api到JarkataEE

### ISSUE THREAD

**Issue by 129duckflew** [lionsoul2014/ip2region#324]
目前SpringBoot3已经迁移Servlet相关api到JarkataEE，是否考虑发布新的版本支持呢？

**Comment by lionsoul2014** [comment]
发错地方了？这个项目不依赖任何 Servlet 相关的 Api

**Comment by 129duckflew** [comment]
> 发错地方了？这个项目不依赖任何 Servlet 相关的 Api
不好意思确实是弄错了，我close一下
