### ISSUE TITLE
nginx 中 识别变量错误

### ISSUE THREAD

**Issue by Horus-K** [lionsoul2014/ip2region#331]
![image](https://github.com/lionsoul2014/ip2region/assets/48319268/4fe6a206-0f52-4603-8b51-eda13fead8aa)
![image](https://github.com/lionsoul2014/ip2region/assets/48319268/268c08f9-c8ef-4580-8923-17bbbf82d90e)
怎么改识别的变量

**Comment by lionsoul2014** [comment]
你可以 at nginx 的 contributor 来看下

**Comment by suruozhong** [comment]
我也想问，请问哥们解决了吗？如果自定义传入IP变量，或者修改

**Comment by suruozhong** [comment]
@wujjpp 老哥，如果修改识别ip的变量，因为是多级代理，目前识别的都是内网IP

**Comment by Horus-K** [comment]
@suruozhong 目前这个不太支持，所以改用这个了https://github.com/Loyalsoldier/geoip

**Comment by suruozhong** [comment]
@Horus-K 好的，谢谢哥们，我研究看看。我原来也是用geoip2，只用了官方MaxMind的IP库，准确度是真的低
