### ISSUE TITLE
能生成只有几个国家的IP段的数据文件吗？

### ISSUE THREAD

**Issue by bwb0101** [lionsoul2014/ip2region#332]
因ip文件大小限制，ip段只需要某些国家，比如：中国，美国 两个国家的所有ip，这样就会造成ip段不连续，生成xdb上会有问题。

这种情况下有解决方法吗？

**Comment by lionsoul2014** [comment]
IP文件最大 4G，应该够你用了。你把原始数据去掉其他部分即可，生成程序会自动合并，IP段必须连续，不连续的部分使用其他补充数据代替即可。

**Comment by bwb0101** [comment]
不是上限限制，是文件越小越好
是不需要的只保留ip部分吗？
如
1.0.1.0|1.0.1.5|cn|电信     正常用的
1.0.1.6|1.0.2.7|-       不使用的
1.0.2.8|1.2.5.5|-      不使用的
...

不用的ip，数据部分用相同字符代替下？
