### ISSUE TITLE
数据准确性

### ISSUE THREAD

**Issue by LuoZijun** [lionsoul2014/ip2region#34]
这条数据是错误的:

```
91.234.36.0|91.234.36.255|德国|0|0|0|0
```

正确数据可以在这个原始文件里面搜索到: https://github.com/ExodusVPN/ip-db/blob/master/data/delegated-ripencc-extended-latest

出现这样的错误，是不是 数据解析脚本有问题呢？

**Comment by LuoZijun** [comment]
好吧，我还是以 IANA 分配的为准。

**Comment by lionsoul2014** [comment]
最早的数据试过IANA的，发现对于国内的错误很多，我自己的几台服务器和家庭网络都定位错误了！

**Comment by LuoZijun** [comment]
是这样子的，IANA 分配的是 IP 的使用权，它里面的 `CN` 之类的国家字段代表这个 `IP` 的使用权在中国（机构或者个人），至于这个 组织或个人 把这个 `IP` 用在哪个地方，则看他自己的意愿。

比如 `91.234.36.0 - 91.234.36.255` 这个 `IP` 段的使用权是属于中国的，但是中国的拥有者 可以把他使用在外国的网络上面，这个可以通过 `traceroute` 来得知。

再比如，谷歌云（Google Cloud）的IP段就是美国的，但是谷歌公司把这些 IP 使用再世界各地的机房，比如日本、台湾、韩国等。

**Comment by LuoZijun** [comment]
所以 IANA 的数据库体现的是`所有权`。你这个阿里的可能体现的是`使用地`。

**Comment by LuoZijun** [comment]
@lionsoul2014 

我想了下，你的这个抓取的数据，我认为也有使用价值，不知你是否愿意公开其中的数据抓取代码以及数据整理代码呢？

我想把它使用在我的 https://github.com/ExodusVPN 项目上（在得到你的许可的情况下）。

另外，我似乎没有看到你的项目当中有 `授权信息` ，你能添加一份吗？

**Comment by lionsoul2014** [comment]
有没有用，就要看你怎么用了。
数据升级程序因为版权问题不会开源，ip2region是Apache 2.0授权协议。程序检测到变动部分超过一定的阈值就会更新，升级的ip2region.db会在git参数同步更新。

**Comment by lionsoul2014** [comment]
项目下有个LISENCE.md

**Comment by LuoZijun** [comment]
明白了，谢谢。
