### ISSUE TITLE
关于线程安全

### ISSUE THREAD

**Issue by liuyunbin** [lionsoul2014/ip2region#345]
大家有考虑写一个直接从 ip.merge.txt 查找的纯内存操作的线程安全的版本吗?
方便后续更新数据文件以及使用

1. 可以提供一个 init() 函数,  由 ip.merge.txt 生成对应的数据结构 -- 这个耗时不重要
2. 可以提供一个 search() 函数, 用于查询 -- 这个部分是线程安全的
3. 可以提供一个 bench() 函数, 用于测速以及验证准确性

**Comment by lionsoul2014** [comment]
你说的这些功能都有，目前的支持内存查找，也是线程安全的

**Comment by liuyunbin** [comment]
确实有,
