### ISSUE TITLE
调用偶现段错误问题

### ISSUE THREAD

**Issue by Summer-Time-2020** [lionsoul2014/ip2region#346]
gdb) bt
#0  0x00007fb560a463b1 in memcpy (__len=18446744073709551614, __src=0x7fb559b382c4, __dest=<optimized out>) at ../mmip2region/ip2region.c:274
#1  ip2region_binary_search (ip2rObj=0x55fe13ffb010, ip=2610686931, datablock=datablock@entry=0x7fb559b38430) at ../mmip2region/ip2region.c:271
#2  0x00007fb560a46907 in ip2region_binary_search_string (ip2rObj=<optimized out>, ip=ip@entry=0x7fb5493ef8d0 "155.155.235.211", datablock=datablock@entry=0x7fb559b38430) at ../mmip2region/ip2region.c:279
#3  0x00007fb560a44d1e in doFunc_Ip2region (func=<optimized out>, ret=0x7fb559b386c0, usrptr=<optimized out>, pWti=<optimized out>) at fmip2region.c:474
#4  0x000055fe1404eb40 in ?? ()
#5  0x00007fb54f230dc0 in ?? ()
#6  0x00007fb560a44d1e in doFunc_Ip2region (func=<optimized out>, ret=0x7fb559b386c0, usrptr=<optimized out>, pWti=<optimized out>) at fmip2region.c:474
#7  0x000055fe1404eb40 in ?? ()
#8  0x00007fb54f230dc0 in ?? ()
#9  0x00007fb560a44d1e in doFunc_Ip2region (func=<optimized out>, ret=0x7fb559b386c0, usrptr=<optimized out>, pWti=<optimized out>) at fmip2region.c:474

**Comment by Summer-Time-2020** [comment]
使用该IP重复调用没有复现

**Comment by lionsoul2014** [comment]
旧版本废弃了，不要再使用了，使用新版本的 xdb。
