### ISSUE TITLE
txt 转 xdb 是报错 failed running genDb: java.lang.Exception: discontinuous data segment

### ISSUE THREAD

**Issue by zhaidw** [lionsoul2014/ip2region#347]
你好，ip2region-maker 代码使用的仓库最新代码。

java -jar ./target/ip2region-maker-1.0.0.jar --src=../../data/ip.merge.txt --dst=./ip2region.xdb

2024-04-25 19:14:07 INFO  org.lionsoul.ip2region.xdb.Maker try to init the db header ...
2024-04-25 19:14:07 INFO  org.lionsoul.ip2region.xdb.Maker try to load the segments ...
2024-04-25 19:14:07 INFO  org.lionsoul.ip2region.xdb.Maker load segment `99.82.179.208|99.82.179.209|AE|AS|||`
2024-04-25 19:14:07 INFO  org.lionsoul.ip2region.xdb.Maker load segment `188.240.81.0|188.240.81.255|AE|AS|||`
failed running genDb: java.lang.Exception: discontinuous data segment: last.eip+1(3169865984) != seg.sip(3169866239, 188.240.81.0)

ip.merge.txt 数据包含如下，请问是格式上的问题吗？

99.82.179.208|99.82.179.209|AE|AS|||
188.240.81.0|188.240.81.255|AE|AS|||
52.94.249.224|52.94.249.239|AE|AS|||
52.93.69.71|52.93.69.71|AE|AS|||
52.93.69.121|52.93.69.121|AE|AS|||
84.235.142.0|84.235.151.255|AE|AS|||
185.201.100.0|185.201.103.255|AE|AS|||
43.175.4.0|43.175.4.255|AE|AS|||

**Comment by leolin49** [comment]
不是格式问题，这个应该就是你的IP段不连续，比如：
> 99.82.179.208|99.82.179.209|AE|AS|||
188.240.81.0|188.240.81.255|AE|AS|||

那么下一个应该从 _**99.82.179.210**_ 开始，而不是 **_188.240.81.0_**

**Comment by lionsoul2014** [comment]
这种不连续的数据可以使用 xdb 编辑器去添加，不要直接去手动修改 ip.merge.txt，这样就不用理会顺序的问题，具体查看 ReadMe 文档。

**Comment by zhaidw** [comment]
这样的数据很多，不可能手工挨个添加，都是不连续的ip段，编辑器有批量转成xdb的方式吗？
数据来源是  https://ipinfo.io ， 注册账户就能下载到 txt 格式的ip数据库。

**Comment by lionsoul2014** [comment]
仔细看文档，看视频
