### ISSUE TITLE
用ip2region做黑名单ip库，多个ip段查询的时候报异常：slice bounds out of range [236256:256]

### ISSUE THREAD

**Issue by ibyxz** [lionsoul2014/ip2region#358]
用ip2region做黑名单ip库，采用golang 版本，只添加一个ip段的时候，查询没问题，多个ip段查询的时候报异常：slice bounds out of range [236256:256]，请大佬们给指点一下

**Comment by ibyxz** [comment]
内容如下：
115.60.52.0|115.60.52.255|0|0|0|0|lvdu|0
115.60.49.0|115.60.49.255|0|0|0|0|lvdu|A

**Comment by lionsoul2014** [comment]
这个数据是要连续的，这个内容补充中间的空白就好，例如：
115.60.52.0|115.60.52.255|0|0|0|0|lvdu|0
115.60.53.0|115.60.48.255|0|0|0|0|0|0
115.60.49.0|115.60.49.255|0|0|0|0|lvdu|A

然后用 0 代表不是即可

**Comment by ibyxz** [comment]
@lionsoul2014 感谢感谢

**Comment by lionsoul2014** [comment]
0.0.0.0 到 255.255.255.255 都需要，没有的就用空数据段补充就好，但是一定要有
