### ISSUE TITLE
ip.merge.txt 达到90万条后，60万条后的所有查找均失败

### ISSUE THREAD

**Issue by haxqer** [lionsoul2014/ip2region#36]
精度精确到县级市（区）后，数据达到90万条。
目前发现问题在于HEADER INDEX 不够，只有8K 。

**Comment by lionsoul2014** [comment]
这个是个好问题。目前header block的存储空间如果不够，是会影响btree算法的查询，调整下生成的header block的大小就OK了，下个版本会增加dbMaker的header block自定义大小支持！

**Comment by lionsoul2014** [comment]
你这边的90W数据，有尝试合并相同地址的ip段吗，也就是连续的ip段，如果他们的地域信息完全相同，然后就合并为一个大段，这样数据了会减少很多，这边ip.merge.txt一开始没合并前也有50W+，合并后就少了很多！过大的增大HEADER INDEX的尺寸也会影响查询性能。

**Comment by haxqer** [comment]
合并过相同地址的ip，90万包括了国外的，删除国外数据后，数据减少到了10万级别。
