### ISSUE TITLE
103.107.104.0 IP段识别错误

### ISSUE THREAD

**Issue by wangyu1314** [lionsoul2014/ip2region#38]
识别到印度了，
ip2region>> 103.107.104.0
20|印度|0|0|0|0 in 0.03735 millseconds

其实是香港的。
ip138.com IP查询(搜索IP地址的地理位置)
您查询的IP:103.107.104.0
本站数据：香港特别行政区
参考数据1：亚太地区亚太地区
参考数据2：APNIC

**Comment by lionsoul2014** [comment]
这个ip地址确实是香港的，应该是更新过程中的问题，会检测升级算法！
