### ISSUE TITLE
城市id查出来都是0

### ISSUE THREAD

**Issue by twang333** [lionsoul2014/ip2region#40]
我看db识别出来城市id都是0，有计划支持吗？我这边可以帮忙。🤦‍♀️

**Comment by twang333** [comment]
反编译了下dbMaker.jar. 感觉getCityId那识别城市id有问题。返回的都是0。谢谢。

**Comment by twang333** [comment]
可以开源dbMarker的源码吗？

**Comment by dhuib2016** [comment]
cityid查到的都是0,有强迫症的同学希望能完善一下。

**Comment by qyzhaojinxi** [comment]
如果能精确到省或者州就好了

**Comment by lionsoul2014** [comment]
这个在生产数据前忘记运行修复程序导致的，前些天已经重新修复提交了最新的db文件。
https://www.oschina.net/news/97214/ip2region-1-6-1-released
