### ISSUE TITLE
 Java heap space

### ISSUE THREAD

**Issue by student123009** [lionsoul2014/ip2region#43]
byte[] iBuffer = new byte[blockLen + blen]; 
java.lang.OutOfMemoryError: Java heap space
这个怎么解决？

**Comment by student123009** [comment]
我现在直接把java文件夹下ip2region包里的所有内容 和  java->data中的db文件   复制到我的项目。
然后main方法测试可以查到城市。
然后tomcat运行就会报下面的错：
ip: 192.168.23.140
java.lang.NegativeArraySizeException
	at cn.richinfo.rcs.rcsoa.component.ip2region.DbSearcher.btreeSearch(DbSearcher.java:243)
	at cn.richinfo.rcs.rcsoa.component.ip2region.DbSearcher.btreeSearch(DbSearcher.java:292)

**Comment by student123009** [comment]
@lionsoul2014

**Comment by kkrgwbj** [comment]
其实这个问题不是库本身的问题，你是不是用的memory查询？memory在多线程下有问题的。因为raf在多个线程并发调用时候，可能没有初始化。所以就报数组下标错误，这个问题解决的最简单办法就是，单例创建这个bean成功时候，默认执行一次虚拟查询，确保raf初始化即可，后续可以并行来调用。

**Comment by lionsoul2014** [comment]
@student123009 这个问题已经确认是并发引起的，Ip2region的实现不是并发安全的，不同的线程需要创建不同的查询对象来使用，或者如果没法控制自己包一个synchronized即可。
