### ISSUE TITLE
关于命名问题

### ISSUE THREAD

**Issue by TheWaWaR** [lionsoul2014/ip2region#45]
`binding` 一般是指一种语言不实现相关逻辑包装了另一种语言的代码，比如 Python 通过 cffi 来包装 C 语言的库。看了下代码现在这几种语言都不是用 binding 的方式实现的，所以叫 `implementation` 或者叫 `impls` 或者叫 `lang`

还有 `python` 实现的文件名不是蛇型小写字母的。

**Comment by dongyado** [comment]
这个问题不必要太纠结，因为有些binding 确实只是封装了一层，比如 php extension，用户根据文档和经验能找到需要的库即可
