### ISSUE TITLE
ip.merge.txt how to transform ip2region.db

### ISSUE THREAD

**Issue by Leibosite** [lionsoul2014/ip2region#5]
please help me!

**Comment by Leibosite** [comment]
嘿嘿，我自己实现了！感谢博客http://dongyado.com/tools/2016/08/18/structure-of-ip2region-database-file/

**Comment by lionsoul2014** [comment]
抱歉，今儿才有时间打开电脑！恩，那篇博客详细的介绍了ip2region的数据文件结构！
