### ISSUE TITLE
What is the source of the database?

### ISSUE THREAD

**Issue by tuangeek** [lionsoul2014/ip2region#56]
It is having a hard time resolving regions other than China based IP address. For example:

example 1 (USA):
```
ip2region>> 8.8.8.8
166|美国|0|0|0|Level3 in 1.308838 millseconds
```

example 2 (Canada):
```
ip2region>> 207.189.25.17
166|美国|0|0|0|0 in 0.139160 millseconds
```

example 3 (Hungary):
```
ip2region>> 91.219.237.244
64|匈牙利|0|0|0|0 in 0.140625 millseconds
```

**Comment by lionsoul2014** [comment]
it's time for me to update the database to get the latest version.  
the data mainly from ip.tabobao.com, the best data source for now.

**Comment by tuangeek** [comment]
Thanks.
