### ISSUE TITLE
关于C#  nuget包引用问题

### ISSUE THREAD

**Issue by realyrare** [lionsoul2014/ip2region#59]
IP2Region 支持.netfx什么版本的？

**Comment by lionsoul2014** [comment]
这个得问下 @RocherKong ，C#的版本是他贡献的。

**Comment by RocherKong** [comment]
@honggangMa 无依赖项，新项目尽量使用.net core

**Comment by honggangMa** [comment]
那这东西看来不支持.netfx吧。

**Comment by RocherKong** [comment]
支持啊，4.6以上

**Comment by honggangMa** [comment]
ok，我的项目还是4.5.1。

**Comment by RocherKong** [comment]
@honggangMa  Just Upgrade version for supporting netfx 4.5 .Please Install-Package IP2Region -Version 1.2.0.

**Comment by windsOne** [comment]
@RocherKong   为什么测试例子无法执行 报索引超过界限

**Comment by RocherKong** [comment]
@windsOne 用的哪个版本？是最新的吗？
