### ISSUE TITLE
最新版ip.merge.txt有部分IP数据不正确

### ISSUE THREAD

**Issue by vnnw** [lionsoul2014/ip2region#6]
最新版ip.merge.txt，有几行的ip起止端不正确，起始ip大于终止ip，如下：

"17.72.133.213";"17.72.127.255";"法国";"0";"0";"0";"0";"";"";""
"103.66.56.166";"103.66.56.106";"印度尼西亚";"0";"0";"0";"0";"";"";""
"103.66.142.9";"103.66.131.255";"泰国";"0";"0";"0";"0";"";"";""
"103.73.172.44";"103.73.168.61";"柬埔寨";"0";"0";"0";"0";"";"";""
"103.75.152.97";"103.75.151.255";"新加坡";"0";"0";"0";"0";"";"";""
"103.76.158.192";"103.76.151.255";"印度尼西亚";"0";"0";"0";"0";"";"";""
"103.82.27.210";"103.80.20.130";"香港";"0";"香港特别行政区";"0";"Hong Kong Internet Exchange";"";"";""
"173.222.109.200";"173.222.102.234";"西班牙";"0";"0";"0";"0";"";"";""

**Comment by lionsoul2014** [comment]
哈哈，应该是修改的升级程序，返回轮询数据导致的赘余数据，感谢反馈！
好奇，请问你是怎么发现的，用你的程序过滤了一遍？

**Comment by vnnw** [comment]
我把数据导到PostgreSQL里面，把ip文本转换INET类型，然后把起止IP设定成INET Range类型。
PG里的Range数据类型，起始值不能大于终止值。
数据库报错，然后就发现了这个问题。

**Comment by lionsoul2014** [comment]
哈哈，谢谢啊，我自己肯定是不会发现这个问题的！
全部的有问题的行都在这里吧？

**Comment by vnnw** [comment]
应该是的。

**Comment by lionsoul2014** [comment]
行，我去确认下，然后再给个提交！

**Comment by lionsoul2014** [comment]
下周一发布的版本重写了升级算法，已经修复了该问题了，敬请期待。
