### ISSUE TITLE
golang sdk 并发问题

### ISSUE THREAD

**Issue by suconghou** [lionsoul2014/ip2region#71]
golang sdk 存在并发安全问题

region 设置为全局变量
```
region, err := ip2region.New(file)
```

后面多次并发调用搜索

BinarySearch:

![QQ20180813-141437@2x.png](https://i.loli.net/2018/08/13/5b7121e2e2e51.png)

BtreeSearch:

![QQ20180813-141551@2x.png](https://i.loli.net/2018/08/13/5b712223802ef.png)

MemorySearch 测试表明是并发安全的

![QQ20180813-141735@2x.png](https://i.loli.net/2018/08/13/5b71228a84e67.png)

**Comment by lionsoul2014** [comment]
Memorysearch也并不是完全意义的线程安全，ip2region的设计就不是线程安全的，多线程情况下，不同线程new 一个独立的对象来操作，完了关闭资源就OK了。
