### ISSUE TITLE
为什么不搞一个sql版本呢

### ISSUE THREAD

**Issue by imsheng** [lionsoul2014/ip2region#73]
rt

**Comment by lionsoul2014** [comment]
没太明白sql版本的意思，是提供一个sql的原始文件吗，还是说通过sql来查询？
通过关系型数据库来查询肯定不行的，很慢！

**Comment by lionsoul2014** [comment]
将ip.merge.txt导入到数据库就OK了。

**Comment by vnnw** [comment]
可以用PostgreSQL来做，支持IP数据的区间索引。

**Comment by vnnw** [comment]
@lionsoul2014 可参考：https://tapoueh.org/blog/2018/08/geolocation-with-postgresql/
