### ISSUE TITLE
nodejs版ip2region是否已经发布到NPM？

### ISSUE THREAD

**Issue by a631807682** [lionsoul2014/ip2region#75]
请问nodejs版ip2region是否已经发布到NPM？
如果已发布，能否给个链接（没找到）。
如果没有，是因为什么原因而不发布上去？

**Comment by lionsoul2014** [comment]
貌似没有发布，这个要怎么发上去，能给个文档吗，我不太熟悉node.js

**Comment by lionsoul2014** [comment]
@dongyado

**Comment by a631807682** [comment]
@lionsoul2014 注册`npm`用户,在本地填好`package.json`执行`npm publish`指令就行了。
[https://docs.npmjs.com/getting-started/publishing-npm-packages](publishing-npm-packages)

**Comment by Maledong** [comment]
考虑你还有一个数据库，所以请注明如何使用，谢谢！

**Comment by a631807682** [comment]
@Maledong 用的数据库文件吧？可以传上去的。
https://docs.npmjs.com/files/package.json#files

**Comment by Maledong** [comment]
哦，我也没有用过。我的意思只是提醒一下还有附件，可能需要加注说明，谢谢你告知

**Comment by liudonghua123** [comment]
已经三年没更新了，里面数据文件的路劲都变了
