### ISSUE TITLE
并发性能问题

### ISSUE THREAD

**Issue by caengcjd** [lionsoul2014/ip2region#77]
大佬你好，我循环几万次查询，发现总共耗时很高(好几秒)，有时候不能忍了，不知道大佬这方面测试了木有呢～
        start_time = time.time()
        for  i  in range(20000):
            start = time.time()
            locations = searcher.memorySearch("182.61.62.41")
        print time.time() - start_time
但是，对比于ipipnet查询不超过1秒，这方面是不是有优化空间呢？感谢哈🙏

**Comment by kkrgwbj** [comment]
你用的是哪个语言的类库？我用的JAVA的单次调用0.xms。循环那么多次执行还没有测试过，今天我到公司测试下。

**Comment by kkrgwbj** [comment]
![image](https://user-images.githubusercontent.com/6836934/44887743-45f3a200-ad00-11e8-9649-a1c4e9335428.png)
这是我执行了100w次 才4s

**Comment by RocherKong** [comment]
没这么慢啊，我的c#客户端百万次耗时1秒5
![csharp100w](http://oohy5l0lw.bkt.clouddn.com/test100w.png)
@caengcjd

**Comment by caengcjd** [comment]
@kkrgwbj,你好我用的Python版本，循环几万次就要几秒，你们再看下？

**Comment by caengcjd** [comment]
@RocherKong,你好我用的Python版本，有问题的

**Comment by kkrgwbj** [comment]
@RocherKong 你的输出在外面   我的输出在里面能一样吗？

**Comment by kkrgwbj** [comment]
![image](https://user-images.githubusercontent.com/6836934/44896941-85d07e80-ad2c-11e8-8307-f151297d0c3d.png)
看清楚了。100w次 560ms

**Comment by caengcjd** [comment]
python2.7,我的测试如下,很有问题
![image](https://user-images.githubusercontent.com/8900898/44911306-03aa7f00-ad59-11e8-8ba0-db7a58b1f7bb.png)

**Comment by caengcjd** [comment]
@kkrgwbj @lionsoul2014 @RocherKong 这个问题头大啊

**Comment by lionsoul2014** [comment]
@caengcjd 把你的代码更下，丢到一个循环里面，不要嵌套循环，最终的结果一次性输出来，也不要在循环里面做io食醋胡。我看了下python binding的代码有些指令过于导致内存的申请和清理，但不至于太差。我回头改下。。

**Comment by lionsoul2014** [comment]
@caengcjd python版本已经合并了，并且优化了性能，本质上是一个bug。
```shell
...
235|中国|0|天津|天津市|鹏博士 in 0.037842 millseconds
235|中国|0|天津|天津市|鹏博士 in 0.035889 millseconds
235|中国|0|天津|天津市|鹏博士 in 0.037842 millseconds
235|中国|0|天津|天津市|鹏博士 in 0.056152 millseconds
235|中国|0|天津|天津市|鹏博士 in 0.036865 millseconds
235|中国|0|天津|天津市|鹏博士 in 0.039307 millseconds
235|中国|0|天津|天津市|鹏博士 in 0.034912 millseconds
235|中国|0|天津|天津市|鹏博士 in 0.037109 millseconds
235|中国|0|天津|天津市|鹏博士 in 0.036865 millseconds
235|中国|0|天津|天津市|鹏博士 in 0.048828 millseconds
235|中国|0|天津|天津市|鹏博士 in 0.037354 millseconds
235|中国|0|天津|天津市|鹏博士 in 0.039062 millseconds
235|中国|0|天津|天津市|鹏博士 in 0.041016 millseconds
235|中国|0|天津|天津市|鹏博士 in 0.035889 millseconds
235|中国|0|天津|天津市|鹏博士 in 0.052002 millseconds
Benchmark done: 1437.599121
lionsoul@lionsoul-ThundeRobot:/data0/code/c/ip2region$ 
```
