### ISSUE TITLE
从classpath中加载数据库文件

### ISSUE THREAD

**Issue by sdvdxl** [lionsoul2014/ip2region#8]
java 怎么从classpath加载文件，

```java
URL dbURL = IpUtils.class.getClassLoader().getResource("data/ip2region.db");
searcher = new DbSearcher(new DbConfig(), dbURL.getFile());
```

这个加载不到，请问怎么解决

**Comment by lionsoul2014** [comment]
DbSearcher内部使用的是RandomeFileAccess，classpath中的输入流是不支持的。
你可以更改下DbSearcher的代码，可以支持memorySearch方式。但是基于文件的b-tree和binary查询的方式将都没法支持！

**Comment by sdvdxl** [comment]
改变了方式，读取classpath的文件流，重新写入一个文件放到磁盘，读取这个文件的绝对路径。

**Comment by lionsoul2014** [comment]
哈哈，这种方式也行，棒棒的！

**Comment by wendal** [comment]
看了一下DbSearcher中RandomeFileAccess的调用,可以抽取一个接口,支持 seed, readFull,close方法就可以了
