### ISSUE TITLE
city_id 匹配兼容性不强

### ISSUE THREAD

**Issue by xenv** [lionsoul2014/ip2region#80]
由于原始数据格式并不统一，导致大量 city_id 无法匹配。比如
有的IP数据是所在地是大理，而csv里面只有大理市，导致 city_id 为 0
还有比如说 阿拉善，csv里面只有 阿拉善盟，city_id 也为 0

**Comment by liupeng1993** [comment]
是的， 不知道作者能不能优化下。

**Comment by lionsoul2014** [comment]
这个是个bug，在新版本里面已经fix了。
