### ISSUE TITLE
ip2region.db 文件放在spring的 resources 中，部署后 ip2region.db文件从6.5M 变为10.9M，从而无法读取

### ISSUE THREAD

**Issue by sqmwin** [lionsoul2014/ip2region#89]

**Comment by sqmwin** [comment]
系统：mac 10.14
版本：spring 4.2.3
ip2region 1.7.2
无论是打包成 war 包还是 jar 包，部署解压后，ip2region.db文件的大小都变了，导致数据错误。
ip2region.db无论是此项目原始的文件还是我用 dbMaker 生成的都出现此情况

**Comment by lionsoul2014** [comment]
ip2regine.db文件不要打包到jar包里面去，直接丢到jar包外面使用即可。而且查询以来ramdonAccess，丢到jar包里面无法使用seek，那只有memory算法可用了！
