### ISSUE TITLE
160.19.212 段不在日本

### ISSUE THREAD

**Issue by jicknan** [lionsoul2014/ip2region#9]
比如 160.19.212.227

ip.taobao.com 查询在日本

ipip.net 查询是正确的：
中国北京 hexinmi.com 联通
AS9929	160.19.212.0/22	CNCNET-CN China Netcom Corp., CN

**Comment by lionsoul2014** [comment]
不知道你是用的哪个版本的数据，最新版本的查询结果如下：

ip2region>> 160.19.212.227
5|日本|0|0|0|0 in 0.09204 millseconds
ip2region>> 

是属于日本的区域

**Comment by jicknan** [comment]
![image](https://cloud.githubusercontent.com/assets/7992/22733408/960b804e-ee2c-11e6-9855-12796390432a.png)
我的意思是，这个IP本来是在国内的。

**Comment by lionsoul2014** [comment]
这个是你们公司的ip断吗？我也不确信哪个数据是对的！

**Comment by jicknan** [comment]
不是我们公司的，但我能确定 ipip.net 的是对的
