### ISSUE TITLE
区域为0

### ISSUE THREAD

**Issue by homcin** [lionsoul2014/ip2region#92]
ip2region-master python binding/python/testSearcher.py ./data/ip2region.db
initializing b-tree...
+----------------------------------+
| ip2region test program           |
| Author: chenxin619315@gmail.com. |
| Type 'quit' to exit program      |
+----------------------------------+
ip2region>> 101.105.35.57
2163|中国|0|广东省|深圳市|鹏博士 in 1.300781 millseconds

很多ip的区域都是0。

**Comment by lionsoul2014** [comment]
这个数据取消了，后期都不会有了，供应商数据缺失！
