### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [lionsoul2014/ip2region#93]
I would like to point out that identifiers like “[`_IP2REGION_H`](https://github.com/lionsoul2014/ip2region/blob/e26ed448618aea6d01f36ed4761dc6c235534c9e/binding/c/ip2region.h#L7 "Update candidate")” and “[`__PRINT_ABOUT__`](https://github.com/lionsoul2014/ip2region/blob/1b275b49da8b8066772a6cb93d494c133868af70/binding/c_mmap/testSearcher.c#L14 "Another update candidate")” [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by lionsoul2014** [comment]
Thanks for ur advice. 
If you try to embed ip2region to a complex C project this do will be a problem, i will make a change in the next release.
