### ISSUE TITLE
建议增加php composer版本的支持

### ISSUE THREAD

**Issue by rungao** [lionsoul2014/ip2region#95]
php 现在大部分都是composer包的方式开发，建议增加composer的方式的支持，之前有类似的人做过，但是不知为何后续就不更新了。

**Comment by lionsoul2014** [comment]
好建议，加上。。。

**Comment by eddy8** [comment]
写了个：https://github.com/eddy8/ip2region

**Comment by liangshuocj** [comment]
找到了一个：https://github.com/zoujingli/ip2region

**Comment by liangshuocj** [comment]
找到了一个：https://github.com/zoujingli/ip2region

**Comment by dongyado** [comment]
https://github.com/zoujingli/ip2region 更新太少，后期会考虑自行发布 composer

**Comment by dongyado** [comment]
建议使用 https://github.com/zoujingli/ip2region 这个同学每次数据更新都很及时
